//monkey
export const names_list: any = {
  b1: 'Gold',
  b2: 'Red',
  b3: 'Blue',
  b4: 'Pink',
  b5: 'Purple',
  b6: 'Green',
  b7: 'Aqua',
  b8: 'Grey',
  t165: 'Rainbow',
  t163: 'Futuristic',
  t164: 'Cheetah',
  t1: 'Gold',
  t2: 'Lava',
  t3: 'Robot',
  t333: 'Pink',
  t4: 'Zombie',
  t5: 'Cream',
  t8: 'Brown',
  t166: 'Dark brown',
  t7: 'Grey',
  t6: 'Red',
  t13: 'Jedi cape',
  t71: 'Neck bolts',
  t16: 'Robot claws',
  t21: 'Knight armour',
  t45: 'Smoking jacket',
  t53: 'Pilot jacket',
  t26: 'Bathrobe',
  t20: 'Captain jacket',
  t18: 'Fur coat',
  t22: 'Jumper',
  t68: 'Dollar chain',
  t33: 'Puffa jacket',
  t48: 'Shirt & sweater',
  t188: 'Mummy',
  t17: 'Military jacket',
  t19: 'Navy jacket',
  t157: 'Spiked armour',
  t15: 'Tuxedo',
  t29: 'Turtleneck jumper',
  t50: 'Body armour',
  t51: 'Dinner suit',
  t69: 'Gold chain',
  t72: 'Clock chain',
  t32: 'Dungarees',
  t408: 'Dress',
  t70: 'Police badge',
  t30: 'Denim jacket',
  t24: 'Leather jacket',
  t43: 'Sports jacket',
  t28: 'Baseball jersey',
  t36: 'Double sword holster',
  t31: 'Basketball jersey',
  t37: 'Bandolier',
  t47: 'High visibility vest',
  t38: 'Waistcoat',
  t42: 'FLAK vest',
  t52: 'Puffer vest',
  t34: 'Striped t-shirt',
  t27: 'Straight jacket',
  t158: 'Greek toga',
  t23: 'Army jacket',
  t35: 'Bulletproof vest',
  t74: 'Bone necklace',
  t44: 'Lumberjack shirt',
  t73: 'Silver chain',
  t39: 'Hoodie',
  t41: 'Hawaiian shirt',
  t25: 'Prison jumpsuit',
  t402: 'Arrow quiver',
  t405: 'Lab jacket',
  t410: 'Leaves',
  t401: 'Dog tags',
  t406: 'Safari shirt',
  t409: 'Camouflage t-shirt',
  t411: 'Tanktop',
  t407: 'Neckerchief',
  t404: 'Caveman pelt',
  t403: 'Claw mark t-shirt',
  t80: 'Silver teeth',
  t78: 'Rainbow teeth',
  t82: 'Missing teeth',
  t76: 'Tongue out',
  t79: 'Gold teeth',
  t83: 'Side smile',
  t380: 'Creepy',
  t378: 'Toxic',
  t383: 'Blood',
  t162: 'Scary smile',
  t382: 'Shocked',
  t381: 'Roar',
  t161: 'Grin',
  t385: 'Fangs',
  t384: 'Confused',
  t379: 'Zombie',
  t109: 'Futuristic',
  t117: 'Blue hypnotised',
  t118: 'Orange hypnotised',
  t107: 'One eye',
  t106: 'Eyeball out',
  t116: 'Cross',
  t119: 'Red hypnotised',
  t108: 'Fire',
  t111: 'Green',
  t115: 'Multicoloured',
  t110: 'Bloodshot',
  t114: 'Sleepy',
  t113: 'Black hypnotised',
  t112: 'Wide eyed',
  t86: 'Bandage',
  t97: 'Eyebrow bar',
  t85: 'Futuristic glasses',
  t99: '3D glasses',
  t87: 'AR glasses',
  t84: 'Cyborg eye',
  t89: 'Masquerade mask',
  t96: 'Eyebrow ring',
  t93: 'Ski mask',
  t88: 'Disco glasses',
  t98: 'Scar',
  t91: 'Aviator glasses',
  t90: 'Bandit mask',
  t95: 'Reading glasses',
  t94: 'Eye patch',
  t92: 'Goggles',
  t160: 'Plague',
  t59: 'Hazard helmet',
  t64: 'Clown',
  t65: 'Horror',
  t55: 'Robot',
  t56: 'Machine',
  t63: 'Leather',
  t58: 'Balaclava',
  t57: 'Half skull',
  t159: 'Oxygen mask',
  t62: 'Half skeleton',
  t61: 'Guy Fawkes',
  t54: 'Cyborg',
  t60: 'Gas mask',
  t100: 'Feather earring',
  t102: 'Stretched earring',
  t105: 'Stud earrings',
  t101: 'Gold earring',
  t103: 'Earphones',
  t104: 'Silver bar earring',
  t66: 'Nose bar',
  t67: 'Nose ring',
  t656: 'Bone',
  t120: 'Crown',
  t146: 'Nightvision helmet',
  t121: 'Roman helmet',
  t123: 'Soccer helmet',
  t124: 'Viking helmet',
  t125: 'Boxing headgear',
  t152: 'Dreadlocks',
  t127: 'Skating helmet',
  t154: 'Mohawk',
  t126: 'Top hat',
  t151: 'Punk hair',
  t153: 'Man bun',
  t137: 'Headphones',
  t131: 'Bowler hat',
  t135: 'Trapper hat',
  t138: 'Vizor hat',
  t140: 'Beenie hat',
  t145: 'Hard hat',
  t143: 'Turban',
  t122: 'Spike helmet',
  t148: 'Long hair',
  t144: 'Beret',
  t130: 'Straw hat',
  t133: 'Pirates hat',
  t128: 'Sailors hat',
  t147: 'Roman leaf crown',
  t129: 'Military hat',
  t134: 'Bobble hat',
  t141: 'Bandana',
  t132: 'Cowboy hat',
  t136: 'Backwards hat',
  t142: 'Baseball hat',
  t139: 'Bucket hat',
  t654: 'Safari hat',
  t655: 'Bamboo hat',
  t999: 'N/A',

};

// panda
// export const names_list: any = {
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//
//   t165: 'Rainbow',
//   t2: 'Lava',
//   t164: 'Cheetah',
//   t163: 'Futuristic',
//   t1: 'Gold',
//   t333: 'Pink',
//   t3: 'Robot',
//   t5: 'Cream',
//   t4: 'Zombie',
//   t8: 'Black',
//   t7: 'Striped',
//   t166: 'Grey',
//   t6: 'Red',
//
//   t13: 'Jedi cape',
//   t53: 'Pilot jacket',
//   t45: 'Smoking jacket',
//   t26: 'Bathrobe',
//   t20: 'Captain jacket',
//   t18: 'Fur coat',
//   t21: 'Knight armour',
//   t22: 'Jumper',
//   t16: 'Robot claws',
//   t71: 'Futuristic',
//   t51: 'Dinner suit',
//   t17: 'Military jacket',
//   t50: 'Body armor',
//   t68: 'Dollar chain',
//   t157: 'Spiked armour',
//   t48: 'Shirt & sweater',
//   t19: 'Navy jacket',
//   t15: 'Tuxedo',
//   t33: 'Puffa jacket',
//   t188: 'Mummy',
//   t405: 'Lab jacket',
//   t402: 'Arrow quiver',
//   t401: 'Dog tags',
//   t34: 'Striped t-shirt',
//   t39: 'Hoodie',
//   t38: 'Waistcoat',
//   t28: 'Baseball jersey',
//   t404: 'Caveman pelt',
//   t24: 'Leather jacket',
//   t52: 'Puffer vest',
//   t41: 'Hawaiian shirt',
//   t74: 'Bone necklace',
//   t27: 'Straight jacket',
//   t403: 'Claw mark t-shirt',
//   t29: 'Turtleneck jumper',
//   t43: 'Sports jacket',
//   t73: 'Silver chain',
//   t25: 'Prison jumpsuit',
//   t42: 'FLAK vest',
//   t35: 'Bulletproof vest',
//   t411: 'Tanktop',
//   t409: 'Camouflage t-shirt',
//   t406: 'Safari shirt',
//   t72: 'Clock chain',
//   t410: 'Leaves',
//   t69: 'Gold chain',
//   t37: 'Bandolier',
//   t407: 'Neckerchief',
//   t158: 'Greek toga',
//   t44: 'Lumberjack shirt',
//   t31: 'Basketball jersey',
//   t23: 'Army jacket',
//   t32: 'Dungarees',
//   t36: 'Double sword holster',
//   t70: 'Police badge',
//   t47: 'High visibility vest',
//   t30: 'Denim jacket',
//   t408: 'Dress',
//
//   t78: 'Rainbow teeth',
//   t80: 'Silver teeth',
//   t79: 'Gold teeth',
//   t76: 'Tongue out',
//   t82: 'Missing teeth',
//   t75: 'Sewn mouth',
//   t161: 'Grin',
//   t81: 'Goofy smile',
//   t162: 'Scary smile',
//   t77: 'Blowing',
//   t83: 'Side smile',
//
//   t111: 'Green',
//   t118: 'Orange hypnotised',
//   t117: 'Blue hypnotised',
//   t363: 'Futuristic',
//   t107: 'One eye',
//   t106: 'Eyeball out',
//   t108: 'Fire',
//   t116: 'Cross',
//   t115: 'Multicoloured',
//   t112: 'Wide eyed',
//   t119: 'Red hypnotised',
//   t114: 'Sleepy',
//   t110: 'Bloodshot',
//   t113: 'Black hypnotised',
//
//   t160: 'Plague',
//   t60: 'Gas mask',
//   t159: 'Oxygen mask',
//   t54: 'Cyborg',
//   t62: 'Half skeleton',
//   t65: 'Horror',
//   t303: 'Machine',
//   t56: 'Jigsaw',
//   t58: 'Balaclava',
//   t63: 'Leather',
//   t64: 'Clown',
//   t59: 'Hazard helmet',
//   t61: 'Guy Fawkes',
//   t57: 'Half skull',
//
//   t101: 'Gold earring',
//   t102: 'Spiked earring',
//   t100: 'Feather earring',
//   t105: 'Stud earrings',
//   t104: 'Silver bar earring',
//   t103: 'Earphones',
//
//   t87: 'AR glasses',
//   t86: 'Bandage',
//   t89: 'Masquerade mask',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t85: 'Robot eye',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t93: 'Ski mask',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t98: 'Scar',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t95: 'Reading glasses',
//   t94: 'Eye patch',
//
//   t67: 'Nose ring',
//   t66: 'Nose bar',
//   t656: 'Bone',
//
//
//   t126: 'Top hat',
//   t151: 'Punk hair',
//   t154: 'Mohawk',
//   t121: 'Roman helmet',
//   t124: 'Viking helmet',
//   t146: 'Nightvision helmet',
//   t152: 'Dreadlocks',
//   t120: 'Crown',
//   t125: 'Boxing headgear',
//   t123: 'Soccer helmet',
//   t145: 'Hard hat',
//   t138: 'Kaffiyeh',
//   t140: 'Beenie hat',
//   t144: 'Beret',
//   t127: 'Skating helmet',
//   t148: 'Long hair',
//   t122: 'Spike helmet',
//   t131: 'Bowler hat',
//   t143: 'Turban',
//   t153: 'Man bun',
//   t137: 'Headphones',
//   t134: 'Bobble hat',
//   t139: 'Bucket hat',
//   t141: 'Bandana',
//   t142: 'Baseball hat',
//   t654: 'Safari hat',
//   t130: 'Straw hat',
//   t128: 'Sailors hat',
//   t147: 'Roman leaf crown',
//   t135: 'Trapper hat',
//   t655: 'Bamboo hat',
//   t129: 'Military hat',
//   t132: 'Cowboy hat',
//   t136: 'Backwards hat',
//   t133: 'Pirates hat',
// };

// hyena
// export const names_list: any = {
//   t999: 'N/A',
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//   t165: 'Rainbow',
//   t2: 'Lava',
//   t164: 'Grey',
//   t163: 'Futuristic',
//   t1: 'Gold',
//   t3: 'Robot',
//   t5: 'Cream',
//   t4: 'Zombie',
//   t333: 'Pink',
//   t8: 'Beige',
//   t7: 'Striped',
//   t166: 'Light brown',
//   t6: 'Red',
//   t13: 'Jedi cape',
//   t71: 'Neck bolts',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t53: 'Pilot jacket',
//   t26: 'Bathrobe',
//   t20: 'Captain jacket',
//   t18: 'Fur coat',
//   t68: 'Dollar chain',
//   t22: 'Jumper',
//   t19: 'Navy jacket',
//   t33: 'Puffa jacket',
//   t188: 'Mummy',
//   t15: 'Tuxedo',
//   t50: 'Body armor',
//   t48: 'Shirt & sweater',
//   t51: 'Dinner suit',
//   t29: 'Turtleneck jumper',
//   t69: 'Gold chain',
//   t72: 'Clock chain',
//   t408: 'Dress',
//   t30: 'Denim jacket',
//   t70: 'Police badge',
//   t28: 'Baseball jersey',
//   t43: 'Sports jacket',
//   t24: 'Leather jacket',
//   t31: 'Basketball jersey',
//   t42: 'FLAK vest',
//   t47: 'High visibility vest',
//   t27: 'Straight jacket',
//   t34: 'Striped t-shirt',
//   t32: 'Dungarees',
//   t52: 'Puffer vest',
//   t37: 'Bandolier',
//   t38: 'Waistcoat',
//   t36: 'Double sword holster',
//   t35: 'Bulletproof vest',
//   t73: 'Silver chain',
//   t17: 'Military jacket',
//   t44: 'Lumberjack shirt',
//   t157: 'Spiked armour',
//   t158: 'Greek toga',
//   t23: 'Army jacket',
//   t74: 'Bone necklace',
//   t25: 'Prison jumpsuit',
//   t39: 'Hoodie',
//   t41: 'Hawaiian shirt',
//   t402: 'Arrow quiver',
//   t1013: 'Tribal tunic',
//   t405: 'Lab jacket',
//   t1012: 'Tribal armor',
//   t406: 'Safari shirt',
//   t401: 'Dog tags',
//   t410: 'Leaves',
//   t644: 'Straw top',
//   t409: 'Camouflage t-shirt',
//   t645: 'Fur waistcoat',
//   t411: 'Tanktop',
//   t712: 'Medieval armour',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t403: 'Claw mark t-shirt',
//   t78: 'Rainbow teeth',
//   t379: 'Zombie',
//   t83: 'Missing teeth',
//   t80: 'Silver teeth',
//   t79: 'Gold teeth',
//   t76: 'Tongue out',
//   t378: 'Toxic',
//   t382: 'Shocked',
//   t385: 'Fangs',
//   t380: 'Creepy',
//   t381: 'Roar',
//   t384: 'Confused',
//   t162: 'Scary smile',
//   t75: 'Sewn mouth',
//   t383: 'Blood',
//   t77: 'Growl',
//   t161: 'Grin',
//   t82: 'Side smile',
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t109: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t111: 'Green',
//   t112: 'Wide eyed',
//   t913: 'One eye closed',
//   t116: 'Cross',
//   t119: 'Red hypnotised',
//   t912: 'Odd',
//   t108: 'Fire',
//   t114: 'Sleepy',
//   t115: 'Multicoloured',
//   t113: 'Black hypnotised',
//   t110: 'Bloodshot',
//   t160: 'Plague',
//   t54: 'Cyborg',
//   t159: 'Oxygen mask',
//   t59: 'Hazard helmet',
//   t60: 'Gas mask',
//   t57: 'Half skull',
//   t634: 'Paw marks',
//   t100: 'Feather earring',
//   t102: 'Spiked earring',
//   t103: 'Earphones',
//   t101: 'Gold earring',
//   t105: 'Stud earrings',
//   t104: 'Silver bar earring',
//   t85: 'Robot eye',
//   t87: 'AR glasses',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t89: 'Masquerade mask',
//   t93: 'Ski mask',
//   t476: 'Eye glass',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t86: 'Bandage',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t95: 'Reading glasses',
//   t94: 'Eye patch',
//   t98: 'Scar',
//   id: 'Nose Wear',
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//   t120: 'Crown',
//   t146: 'Nightvision helmet',
//   t121: 'Roman helmet',
//   t123: 'Soccer helmet',
//   t124: 'Viking helmet',
//   t125: 'Boxing headgear',
//   t154: 'Mohawk',
//   t126: 'Combat helmet',
//   t151: 'Punk hair',
//   t153: 'Man bun',
//   t137: 'Headphones',
//   t152: 'Dreadlocks',
//   t127: 'Skating helmet',
//   t148: 'Long hair',
//   t143: 'Turban',
//   t122: 'Spike helmet',
//   t135: 'Trapper hat',
//   t861: 'Wizards hat',
//   t131: 'Bowler hat',
//   t129: 'Military hat',
//   t138: 'Vizor hat',
//   t128: 'Sailors hat',
//   t140: 'Beenie hat',
//   t133: 'Pirates hat',
//   t145: 'Flat cap',
//   t136: 'Backwards hat',
//   t134: 'Bobble hat',
//   t139: 'Bucket hat',
//   t862: 'Horns',
//   t144: 'Beret',
//   t142: 'Baseball hat',
//   t132: 'Cowboy hat',
//   t1011: 'Twill cap',
//   t130: 'Straw hat',
//   t147: 'Roman leaf crown',
//   t141: 'Bandana',
//   t1488: 'Fedora',
//   t654: 'Safari hat',
//   t655: 'Bamboo hat',
// };

// cheetah
// export const names_list: any = {
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//   t164: 'Striped',
//   t163: 'Futuristic',
//   t165: 'Rainbow',
//   t2: 'Lava',
//   t1: 'Gold',
//   t4: 'Zombie',
//   t3: 'Robot',
//   t5: 'Cream',
//   t333: 'Pink',
//   t7: 'Grey',
//   t6: 'Red',
//   t8: 'Light brown',
//   t166: 'Dark brown',
//   t13: 'Jedi cape',
//   t109: 'Futuristic',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t53: 'Pilot jacket',
//   t26: 'Bathrobe',
//   t18: 'Fur coat',
//   t20: 'Captain jacket',
//   t22: 'Jumper',
//   t68: 'Dollar chain',
//   t19: 'Navy jacket',
//   t188: 'Mummy',
//   t17: 'Military jacket',
//   t157: 'Spiked armour',
//   t15: 'Tuxedo',
//   t33: 'Puffa jacket',
//   t51: 'Dinner suit',
//   t50: 'Body armor',
//   t48: 'Shirt & sweater',
//   t29: 'Turtleneck jumper',
//   t72: 'Clock chain',
//   t69: 'Gold chain',
//   t408: 'Dress',
//   t30: 'Denim jacket',
//   t70: 'Police badge',
//   t28: 'Baseball jersey',
//   t24: 'Leather jacket',
//   t43: 'Sports jacket',
//   t36: 'Double sword holster',
//   t37: 'Bandolier',
//   t31: 'Basketball jersey',
//   t42: 'FLAK vest',
//   t34: 'Striped t-shirt',
//   t47: 'High visibility vest',
//   t27: 'Straight jacket',
//   t32: 'Dungarees',
//   t158: 'Greek toga',
//   t38: 'Waistcoat',
//   t23: 'Army jacket',
//   t52: 'Puffer vest',
//   t35: 'Bulletproof vest',
//   t44: 'Lumberjack shirt',
//   t73: 'Silver chain',
//   t74: 'Bone necklace',
//   t41: 'Hawaiian shirt',
//   t39: 'Hoodie',
//   t402: 'Arrow quiver',
//   t1012: 'Tribal armor',
//   t25: 'Prison jumpsuit',
//   t405: 'Lab jacket',
//   t1013: 'Tribal tunic',
//   t406: 'Safari shirt',
//   t401: 'Dog tags',
//   t410: 'Leaves',
//   t644: 'Straw top',
//   t409: 'Camouflage t-shirt',
//   t645: 'Fur waistcoat',
//   t411: 'Tanktop',
//   t712: 'Medieval armour',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t403: 'Claw mark t-shirt',
//   t161: 'Tongue out',
//   t162: 'Missing teeth',
//   t378: 'Rainbow teeth',
//   t379: 'Gold teeth',
//   t380: 'Zombie',
//   t381: 'Silver teeth',
//   t382: 'Creepy',
//   t383: 'Roar',
//   t384: 'Fangs',
//   t385: 'Toxic',
//   t75: 'Confused',
//   t76: 'Shocked',
//   t77: 'Grin',
//   t78: 'Blood',
//   t79: 'Sewn mouth',
//   t80: 'Growl',
//   t82: 'Scary smile',
//   t83: 'Side smile',
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t912: 'Odd',
//   t118: 'Orange hypnotised',
//   t71: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t913: 'One eye closed',
//   t119: 'Red hypnotised',
//   t112: 'Wide eyed',
//   t111: 'Green',
//   t114: 'Sleepy',
//   t108: 'Fire',
//   t115: 'Multicoloured',
//   t116: 'Cross',
//   t113: 'Black hypnotised',
//   t110: 'Bloodshot',
//   t160: 'Plague',
//   t59: 'Hazard helmet',
//   t58: 'Balaclava',
//   t159: 'Oxygen mask',
//   t54: 'Cyborg',
//   t62: 'Half skeleton',
//   t60: 'Gas mask',
//   t63: 'Leather',
//   t634: 'Paw marks',
//   t55: 'Robot',
//   t65: 'Horror',
//   t64: 'Clown',
//   t61: 'Guy Fawkes',
//   t56: 'Jigsaw',
//   t57: 'Half skull',
//   t100: 'Feather earring',
//   t102: 'Spiked earring',
//   t101: 'Gold earring',
//   t103: 'Earphones',
//   t105: 'Stud earrings',
//   t104: 'Silver bar earring',
//   t85: 'Robot eye',
//   t87: 'AR glasses',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t86: 'Bandage',
//   t89: 'Masquerade mask',
//   t93: 'Ski mask',
//   t476: 'Eye glass',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t94: 'Eye patch',
//   t95: 'Reading glasses',
//   t98: 'Scar',
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//   t120: 'Crown',
//   t146: 'Nightvision helmet',
//   t123: 'Soccer helmet',
//   t124: 'Viking helmet',
//   t125: 'Boxing headgear',
//   t153: 'Man bun',
//   t152: 'Dreadlocks',
//   t127: 'Skating helmet',
//   t137: 'Headphones',
//   t154: 'Mohawk',
//   t151: 'Punk hair',
//   t122: 'Spike helmet',
//   t145: 'Kaffiyeh',
//   t148: 'Long hair',
//   t121: 'Flat cap',
//   t129: 'Military hat',
//   t126: 'Beret',
//   t135: 'Trapper hat',
//   t144: 'Hard hat',
//   t861: 'Wizards hat',
//   t131: 'Bowler hat',
//   t128: 'Sailors hat',
//   t138: 'Vizor hat',
//   t140: 'Beenie hat',
//   t143: 'Turban',
//   t133: 'Pirates hat',
//   t862: 'Horns',
//   t141: 'Bandana',
//   t147: 'Roman leaf crown',
//   t132: 'Cowboy hat',
//   t130: 'Straw hat',
//   t139: 'Bucket hat',
//   t136: 'Backwards hat',
//   t1011: 'Twill cap',
//   t142: 'Baseball hat',
//   t1148: 'Fedora',
//   t134: 'Bobble hat',
//   t654: 'Safari hat',
//   t655: 'Bamboo hat',
//   t999: 'N/A',
// };

// koala
// export const names_list: any = {
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//
//   t1: 'Gold',
//   t2: 'Lava',
//   t165: 'Rainbow',
//   t163: 'Futuristic',
//   t164: 'Cheetah',
//   t4: 'Zombie',
//   t3: 'Robot',
//   t333: 'Pink',
//   t5: 'Cream',
//   t6: 'Red',
//   t7: 'Striped',
//   t166: 'Dark grey',
//   t8: 'Grey',
//
//   t76: 'Tongue out',
//   t83: 'Missing teeth',
//   t78: 'Rainbow teeth',
//   t79: 'Gold teeth',
//   t80: 'Silver teeth',
//   t81: 'Goofy smile',
//   t161: 'Grin',
//   t162: 'Scary smile',
//   t75: 'Sewn mouth',
//   t82: 'Side smile',
//   t77: 'Blowing',
//
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t109: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t111: 'Green',
//   t108: 'Fire',
//   t115: 'Multicoloured',
//   t116: 'Cross',
//   t119: 'Red hypnotised',
//   t112: 'Wide eyed',
//   t114: 'Sleepy',
//   t110: 'Bloodshot',
//   t113: 'Black hypnotised',
//
//   t160: 'Plague',
//   t59: 'Hazard helmet',
//   t64: 'Clown',
//   t65: 'Machine',
//   t55: 'Robot',
//   t56: 'Jigsaw',
//   t58: 'Balaclava',
//   t159: 'Oxygen mask',
//   t61: 'Guy Fawkes',
//   t54: 'Cyborg',
//   t62: 'Half skeleton',
//   t57: 'Half skull',
//   t60: 'Gas mask',
//   t63: 'Leather',
//
//   t102: 'Spiked earring',
//   t100: 'Feather earring',
//   t101: 'Gold earring',
//   t103: 'Earphones',
//   t104: 'Silver bar earring',
//   t105: 'Stud earrings',
//
//   t85: 'Robot eye',
//   t87: 'AR glasses',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t86: 'Bandage',
//   t89: 'Masquerade mask',
//   t93: 'Ski mask',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t94: 'Eye patch',
//   t95: 'Reading glasses',
//   t98: 'Scar',
//
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//
//   t13: 'Jedi cape',
//   t71: 'Neck bolts',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t53: 'Pilot jacket',
//   t26: 'Bathrobe',
//   t18: 'Fur coat',
//   t20: 'Captain jacket',
//   t22: 'Jumper',
//   t68: 'Dollar chain',
//   t188: 'Mummy',
//   t19: 'Navy jacket',
//   t17: 'Military jacket',
//   t33: 'Puffa jacket',
//   t15: 'Tuxedo',
//   t157: 'Spiked armour',
//   t51: 'Dinner suit',
//   t48: 'Shirt & sweater',
//   t50: 'Body armor',
//   t72: 'Clock chain',
//   t69: 'Gold chain',
//   t29: 'Turtleneck jumper',
//   t30: 'Denim jacket',
//   t70: 'Police badge',
//   t408: 'Dress',
//   t28: 'Baseball jersey',
//   t24: 'Leather jacket',
//   t43: 'Sports jacket',
//   t31: 'Basketball jersey',
//   t36: 'Double sword holster',
//   t37: 'Bandolier',
//   t42: 'FLAK vest',
//   t32: 'Dungarees',
//   t27: 'Straight jacket',
//   t158: 'Greek toga',
//   t47: 'High visibility vest',
//   t34: 'Striped t-shirt',
//   t23: 'Army jacket',
//   t52: 'Puffer vest',
//   t38: 'Waistcoat',
//   t35: 'Bulletproof vest',
//   t74: 'Bone necklace',
//   t44: 'Lumberjack shirt',
//   t73: 'Silver chain',
//   t25: 'Prison jumpsuit',
//   t39: 'Hoodie',
//   t41: 'Hawaiian shirt',
//   t402: 'Arrow quiver',
//   t405: 'Lab jacket',
//   t410: 'Leaves',
//   t401: 'Dog tags',
//   t406: 'Safari shirt',
//   t409: 'Camouflage t-shirt',
//   t411: 'Tanktop',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t403: 'Claw mark t-shirt',
//
//   t120: 'Crown',
//   t146: 'Nightvision helmet',
//   t121: 'Roman helmet',
//   t123: 'Soccer helmet',
//   t124: 'Viking helmet',
//   t125: 'Boxing headgear',
//   t152: 'Dreadlocks',
//   t127: 'Skating helmet',
//   t154: 'Mohawk',
//   t126: 'Combat helmet',
//   t151: 'Punk hair',
//   t135: 'Trapper hat',
//   t153: 'Man bun',
//   t137: 'Headphones',
//   t131: 'Bowler hat',
//   t129: 'Military hat',
//   t138: 'Vizor hat',
//   t128: 'Sailors hat',
//   t140: 'Beenie hat',
//   t145: 'Kaffiyeh',
//   t133: 'Pirates hat',
//   t143: 'Turban',
//   t148: 'Long hair',
//   t144: 'Beret',
//   t141: 'Bandana',
//   t132: 'Cowboy hat',
//   t130: 'Straw hat',
//   t147: 'Roman leaf crown',
//   t122: 'Spike helmet',
//   t139: 'Bucket hat',
//   t142: 'Baseball hat',
//   t136: 'Backwards hat',
//   t134: 'Bobble hat',
//   t654: 'Safari hat',
//   t655: 'Bamboo hat',
// };

// elephant
// export const names_list: any = {
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//   t163: 'Futuristic',
//   t2: 'Lava',
//   t164: 'Cheetah',
//   t165: 'Rainbow',
//   t1: 'Gold',
//   t333: 'Pink',
//   t3: 'Robot',
//   t5: 'Cream',
//   t4: 'Zombie',
//   t6: 'Red',
//   t7: 'Striped',
//   t8: 'Grey',
//   t166: 'Dark grey',
//   t13: 'Jedi cape',
//   t71: 'Futuristic',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t53: 'Pilot jacket',
//   t26: 'Bathrobe',
//   t18: 'Fur coat',
//   t20: 'Captain jacket',
//   t22: 'Jumper',
//   t68: 'Dollar chain',
//   t19: 'Navy jacket',
//   t17: 'Military jacket',
//   t188: 'Mummy',
//   t33: 'Puffa jacket',
//   t15: 'Tuxedo',
//   t157: 'Spiked armour',
//   t48: 'Shirt & sweater',
//   t50: 'Body armor',
//   t51: 'Dinner suit',
//   t72: 'Clock chain',
//   t69: 'Gold chain',
//   t29: 'Turtleneck jumper',
//   t30: 'Denim jacket',
//   t408: 'Dress',
//   t70: 'Police badge',
//   t24: 'Leather jacket',
//   t28: 'Baseball jersey',
//   t43: 'Sports jacket',
//   t37: 'Bandolier',
//   t36: 'Double sword holster',
//   t31: 'Basketball jersey',
//   t42: 'FLAK vest',
//   t34: 'Striped t-shirt',
//   t27: 'Straight jacket',
//   t32: 'Dungarees',
//   t47: 'High visibility vest',
//   t158: 'Greek toga',
//   t23: 'Army jacket',
//   t52: 'Puffer vest',
//   t38: 'Waistcoat',
//   t35: 'Bulletproof vest',
//   t74: 'Bone necklace',
//   t44: 'Lumberjack shirt',
//   t73: 'Silver chain',
//   t39: 'Hoodie',
//   t1013: 'Tribal tunic',
//   t41: 'Hawaiian shirt',
//   t402: 'Arrow quiver',
//   t25: 'Prison jumpsuit',
//   t405: 'Lab jacket',
//   t1012: 'Tribal armor',
//   t406: 'Safari shirt',
//   t401: 'Dog tags',
//   t410: 'Leaves',
//   t644: 'Straw top',
//   t409: 'Camouflage t-shirt',
//   t645: 'Fur waistcoat',
//   t411: 'Tanktop',
//   t712: 'Medieval armour',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t403: 'Claw mark t-shirt',
//   t76: 'Tongue out',
//   t83: 'Missing teeth',
//   t78: 'Rainbow teeth',
//   t79: 'Gold teeth',
//   t379: 'Zombie',
//   t80: 'Silver teeth',
//   t380: 'Creepy',
//   t381: 'Roar',
//   t385: 'Fangs',
//   t378: 'Toxic',
//   t384: 'Confused',
//   t382: 'Shocked',
//   t161: 'Grin',
//   t383: 'Blood',
//   t75: 'Sewn mouth',
//   t162: 'Scary smile',
//   t82: 'Side smile',
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t109: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t913: 'One eye closed',
//   t111: 'Green',
//   t108: 'Fire',
//   t112: 'Wide eyed',
//   t912: 'Odd',
//   t115: 'Multicoloured',
//   t116: 'Cross',
//   t114: 'Sleepy',
//   t119: 'Red hypnotised',
//   t113: 'Black hypnotised',
//   t110: 'Bloodshot',
//   t159: 'Machine',
//   t160: 'Plague',
//   t54: 'Cyborg',
//   t59: 'Hazard helmet',
//   t58: 'Balaclava',
//   t63: 'Leather',
//   t60: 'Gas mask',
//   t634: 'Paw marks',
//   t62: 'Half skeleton',
//   t65: 'Horror',
//   t64: 'Clown',
//   t55: 'Robot',
//   t57: 'Half skull',
//   t61: 'Guy Fawkes',
//   t56: 'Jigsaw',
//   t100: 'Feather earring',
//   t102: 'Spiked earring',
//   t103: 'Earphones',
//   t101: 'Gold earring',
//   t105: 'Stud earrings',
//   t104: 'Gold bar earring',
//   t85: 'Robot eye',
//   t87: 'AR glasses',
//   t99: '3D glasses',
//   t97: 'Eyebrow bar',
//   t86: 'Bandage',
//   t89: 'Sunglasses',
//   t93: 'Ski mask',
//   t476: 'Eye glass',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t95: 'Reading glasses',
//   t94: 'Eye patch',
//   t98: 'Scar',
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//   t120: 'Crown',
//   t146: 'Nightvision helmet',
//   t121: 'Roman helmet',
//   t123: 'Soccer helmet',
//   t124: 'Viking helmet',
//   t125: 'Boxing headgear',
//   t152: 'Dreadlocks',
//   t127: 'Skating helmet',
//   t153: 'Man bun',
//   t154: 'Mohawk',
//   t151: 'Punk hair',
//   t148: 'Long hair',
//   t137: 'Headphones',
//   t145: 'Combat helmet',
//   t122: 'Spike helmet',
//   t129: 'Military hat',
//   t135: 'Trapper hat',
//   t131: 'Top hat',
//   t143: 'Turban',
//   t861: 'Wizards hat',
//   t134: 'Bobble hat',
//   t144: 'Hard hat',
//   t128: 'Sailors hat',
//   t138: 'Vizor hat',
//   t133: 'Pirates hat',
//   t862: 'Horns',
//   t139: 'Bucket hat',
//   t136: 'Backwards hat',
//   t140: 'Beenie hat',
//   t147: 'Roman leaf crown',
//   t130: 'Straw hat',
//   t142: 'Baseball hat',
//   t126: 'Beret',
//   t132: 'Cowboy hat',
//   t1011: 'Twill cap',
//   t141: 'Bandana',
//   t654: 'Safari hat',
//   t1488: 'Fedora',
//   t655: 'Bamboo hat',
//   t999: 'N/A',
// };

// warthog
// export const names_list: any = {
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//   t163: 'Futuristic',
//   t1: 'Gold',
//   t164: 'Cheetah',
//   t165: 'Rainbow',
//   t2: 'Lava',
//   t333: 'Pink',
//   t5: 'Cream',
//   t4: 'Zombie',
//   t3: 'Robot',
//   t8: 'Brown',
//   t166: 'Dark brown',
//   t6: 'Red',
//   t7: 'Grey',
//   t18: 'Fur coat',
//   t20: 'Captain jacket',
//   t45: 'Smoking jacket',
//   t26: 'Bathrobe',
//   t71: 'Futuristic',
//   t32: 'Dungarees',
//   t21: 'Knight armour',
//   t38: 'Waistcoat',
//   t16: 'Robot claws',
//   t53: 'Pilot jacket',
//   t13: 'Jedi cape',
//   t33: 'Puffa jacket',
//   t157: 'Spiked armour',
//   t47: 'High visibility vest',
//   t48: 'Shirt & sweater',
//   t22: 'Jumper',
//   t68: 'Dollar chain',
//   t17: 'Military jacket',
//   t188: 'Mummy',
//   t19: 'Navy jacket',
//   t52: 'Puffer vest',
//   t25: 'Prison jumpsuit',
//   t72: 'Clock chain',
//   t407: 'Neckerchief',
//   t822: 'Ripped t-shirt',
//   t34: 'Striped t-shirt',
//   t409: 'Camouflage t-shirt',
//   t29: 'Turtleneck jumper',
//   t712: 'Medieval armour',
//   t1013: 'Tribal tunic',
//   t645: 'Fur waistcoat',
//   t404: 'Caveman pelt',
//   t74: 'Bone necklace',
//   t36: 'Double sword holster',
//   t31: 'Basketball jersey',
//   t405: 'Lab jacket',
//   t37: 'Bandolier',
//   t28: 'Baseball jersey',
//   t27: 'Straight jacket',
//   t402: 'Arrow quiver',
//   t35: 'Bulletproof vest',
//   t1012: 'Tribal armour',
//   t408: 'Dress',
//   t73: 'Silver chain',
//   t70: 'Police badge',
//   t411: 'Tanktop',
//   t30: 'Denim jacket',
//   t15: 'Tuxedo',
//   t406: 'Safari shirt',
//   t24: 'Leather jacket',
//   t403: 'Claw mark t-shirt',
//   t44: 'Lumberjack shirt',
//   t42: 'FLAK vest',
//   t41: 'Hawaiian shirt',
//   t410: 'Leaves',
//   t39: 'Hoodie',
//   t158: 'Greek toga',
//   t401: 'Dog tags',
//   t43: 'Sports jacket',
//   t644: 'Straw top',
//   t23: 'Army jacket',
//   t69: 'Gold chain',
//   t50: 'Body armour',
//   t51: 'Dinner suit',
//   t83: 'Missing teeth',
//   t79: 'Gold teeth',
//   t379: 'Zombie',
//   t78: 'Rainbow teeth',
//   t76: 'Tongue out',
//   t381: 'Roar',
//   t378: 'Toxic',
//   t385: 'Fangs',
//   t380: 'Creepy',
//   t80: 'Silver teeth',
//   t383: 'Blood',
//   t75: 'Sewn mouth',
//   t161: 'Grin',
//   t82: 'Side smile',
//   t162: 'Scary smile',
//   t382: 'Shocked',
//   t912: 'Odd',
//   t109: 'Futuristic',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t106: 'Eyeball out',
//   t913: 'One eye closed',
//   t108: 'Fire',
//   t115: 'Multicoloured',
//   t117: 'Blue hypnotised',
//   t111: 'Green',
//   t113: 'Black hypnotised',
//   t112: 'Wide eyed',
//   t110: 'Bloodshot',
//   t116: 'Cross',
//   t114: 'Sleepy',
//   t119: 'Red hypnotised',
//   t634: 'Paw marks',
//   t160: 'Plague',
//   t58: 'Balaclava',
//   t55: 'Oxygen mask',
//   t59: 'Hazard helmet',
//   t102: 'Spiked earring',
//   t100: 'Feather earring',
//   t103: 'Earphones',
//   t101: 'Gold earring',
//   t105: 'Stud earrings',
//   t104: 'Silver bar earring',
//   t86: 'Bandage',
//   t87: 'AR glasses',
//   t476: 'Eye glass',
//   t99: '3D glasses',
//   t89: 'Sunglasses',
//   t97: 'Eyebrow bar',
//   t85: 'Robot eye',
//   t96: 'Eyebrow ring',
//   t90: 'Bandit mask',
//   t93: 'Ski mask',
//   t88: 'Disco glasses',
//   t84: 'Cyborg eye',
//   t91: 'Aviator glasses',
//   t94: 'Eye patch',
//   t98: 'Scar',
//   t95: 'Reading glasses',
//   t92: 'Goggles',
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//   t154: 'Mohawk',
//   t151: 'Punk hair',
//   t148: 'Long hair',
//   t120: 'Crown',
//   t127: 'Skating helmet',
//   t125: 'Boxing headgear',
//   t121: 'Roman helmet',
//   t131: 'Top hat',
//   t126: 'Bowler hat',
//   t152: 'Dreadlocks',
//   t146: 'Nightvision helmet',
//   t124: 'Viking helmet',
//   t145: 'Combat helmet',
//   t861: 'Wizards hat',
//   t128: 'Sailors hat',
//   t137: 'Headphones',
//   t143: 'Turban',
//   t122: 'Spike helmet',
//   t129: 'Military hat',
//   t138: 'Keffiyeh',
//   t136: 'Backwards hat',
//   t132: 'Cowboy hat',
//   t140: 'Beenie hat',
//   t1148: 'Fedora',
//   t133: 'Pirates hat',
//   t655: 'Bamboo hat',
//   t862: 'Horns',
//   t147: 'Roman leaf crown',
//   t130: 'Straw hat',
//   t134: 'Flat cap',
//   t142: 'Baseball hat',
//   t1011: 'Twill cap',
//   t654: 'Safari hat',
//   t141: 'Bandana',
//   t139: 'Bucket hat',
//   t135: 'Trapper hat',
//   t144: 'Hard hat',
//   t999: 'N/A',
// };

// rhino
// export const names_list: any = {
//   t101: 'Gold earring',
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//   t163: 'Futuristic',
//   t164: 'Cheetah',
//   t165: 'Rainbow',
//   t2: 'Lava',
//   t1: 'Gold',
//   t3: 'Robot',
//   t5: 'Cream',
//   t333: 'Pink',
//   t4: 'Zombie',
//   t7: 'Striped',
//   t8: 'Grey',
//   t166: 'Dark grey',
//   t6: 'Red',
//   t13: 'Jedi cape',
//   t109: 'Futuristic',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t53: 'Pilot jacket',
//   t26: 'Bathrobe',
//   t18: 'Fur coat',
//   t20: 'Captain jacket',
//   t22: 'Jumper',
//   t188: 'Mummy',
//   t68: 'Dollar chain',
//   t17: 'Military jacket',
//   t19: 'Navy jacket',
//   t33: 'Puffa jacket',
//   t50: 'Body armour',
//   t15: 'Tuxedo',
//   t157: 'Spiked armour',
//   t48: 'Shirt & sweater',
//   t69: 'Gold chain',
//   t51: 'Dinner suit',
//   t30: 'Denim jacket',
//   t72: 'Clock chain',
//   t29: 'Turtleneck jumper',
//   t43: 'Sports jacket',
//   t70: 'Police badge',
//   t28: 'Baseball jersey',
//   t408: 'Dress',
//   t24: 'Leather jacket',
//   t31: 'Basketball jersey',
//   t36: 'Double sword holster',
//   t37: 'Bandolier',
//   t42: 'FLAK vest',
//   t678: 'T-shirt',
//   t32: 'Dungarees',
//   t35: 'Bulletproof vest',
//   t47: 'High visibility vest',
//   t23: 'Army jacket',
//   t158: 'Greek toga',
//   t27: 'Straight jacket',
//   t34: 'Striped t-shirt',
//   t39: 'Hoodie',
//   t1012: 'Tribal armour',
//   t38: 'Waistcoat',
//   t52: 'Puffer vest',
//   t41: 'Hawaiian shirt',
//   t677: 'Ripped t-shirt',
//   t74: 'Bone necklace',
//   t73: 'Silver chain',
//   t402: 'Arrow quiver',
//   t44: 'Lumberjack shirt',
//   t1013: 'Tribal tunic',
//   t410: 'Leaves',
//   t25: 'Prison jumpsuit',
//   t401: 'Dog tags',
//   t644: 'Straw top',
//   t405: 'Lab jacket',
//   t409: 'Camouflage t-shirt',
//   t645: 'Fur waistcoat',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t712: 'Medieval armour',
//   t406: 'Safari shirt',
//   t411: 'Tanktop',
//   t403: 'Claw mark t-shirt',
//   t999: 'N/A',
//   t379: 'Zombie',
//   t75: 'Sewn mouth',
//   t79: 'Gold teeth',
//   t78: 'Rainbow teeth',
//   t83: 'Missing teeth',
//   t76: 'Tongue out',
//   t161: 'Grin',
//   t80: 'Silver teeth',
//   t383: 'Blood',
//   t385: 'Fangs',
//   t380: 'Creepy',
//   t381: 'Roar',
//   t82: 'Side smile',
//   t384: 'Confused',
//   t382: 'Shocked',
//   t162: 'Scary smile',
//   t378: 'Toxic',
//   t77: 'Growl',
//   t71: 'Futuristic',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t913: 'One eye closed',
//   t106: 'Eyeball out',
//   t912: 'Odd',
//   t119: 'Red hypnotised',
//   t117: 'Blue hypnotised',
//   t108: 'Fire',
//   t111: 'Green',
//   t113: 'Black hypnotised',
//   t114: 'Sleepy',
//   t115: 'Multicoloured',
//   t110: 'Bloodshot',
//   t116: 'Cross',
//   t112: 'Wide eyed',
//   t58: 'Balaclava',
//   t160: 'Plague',
//   t634: 'Paw marks',
//   t57: 'Half skull',
//   t159: 'Oxygen mask',
//   t60: 'Gas mask',
//   t102: 'Spiked earring',
//   t100: 'Feather earring',
//   t103: 'Earphones',
//   t105: 'Stud earrings',
//   t104: 'Silver bar earring',
//   t476: 'Eye glass',
//   t87: 'AR glasses',
//   t99: '3D glasses',
//   t85: 'Robot eye',
//   t86: 'Bandage',
//   t97: 'Eyebrow bar',
//   t612: 'Futuristic glasses',
//   t84: 'Cyborg eye',
//   t96: 'Eyebrow ring',
//   t89: 'Masquerade mask',
//   t93: 'Ski mask',
//   t611: 'Sunglasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t95: 'Reading glasses',
//   t92: 'Goggles',
//   t98: 'Scar',
//   t94: 'Eye patch',
//   t88: 'Disco glasses',
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//   t1148: 'Fedora',
//   t127: 'Skating helmet',
//   t152: 'Dreadlocks',
//   t154: 'Mohawk',
//   t123: 'Soccer helmet',
//   t120: 'Crown',
//   t126: 'Combat helmet',
//   t125: 'Boxing headgear',
//   t146: 'Nightvision helmet',
//   t124: 'Viking helmet',
//   t861: 'Wizards hat',
//   t862: 'Horns',
//   t121: 'Roman helmet',
//   t1011: 'Twill cap',
//   t911: 'Flat cap',
//   t151: 'Punk hair',
//   t138: 'Vizor hat',
//   t131: 'Top hat',
//   t135: 'Trapper hat',
//   t137: 'Headphones',
//   t128: 'Sailors hat',
//   t129: 'Military hat',
//   t153: 'Man bun',
//   t148: 'Long hair',
//   t872: 'Beret',
//   t140: 'Beenie hat',
//   t122: 'Spike helmet',
//   t136: 'Backwards hat',
//   t139: 'Bucket hat',
//   t654: 'Safari hat',
//   t141: 'Bandana',
//   t144: 'Hard hat',
//   t655: 'Bamboo hat',
//   t134: 'Bobble hat',
//   t133: 'Pirates hat',
//   t147: 'Roman leaf crown',
//   t132: 'Cowboy hat',
//   t142: 'Baseball hat',
//   t143: 'Turban',
//   t145: 'Keffiyeh',
//   t130: 'Straw hat',
// };

//lion
// export const names_list: any = {
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//   t164: 'Grey',
//   t2: 'Lava',
//   t163: 'Futuristic',
//   t165: 'Rainbow',
//   t1: 'Gold',
//   t333: 'Pink',
//   t5: 'Cream',
//   t3: 'Robot',
//   t4: 'Zombie',
//   t8: 'Light brown',
//   t166: 'Brown',
//   t7: 'Striped',
//   t6: 'Red',
//   t53: 'Pilot jacket',
//   t45: 'Smoking jacket',
//   t16: 'Robot claws',
//   t109: 'Futuristic',
//   t13: 'Jedi cape',
//   t33: 'Puffa jacket',
//   t18: 'Fur coat',
//   t48: 'Shirt & sweater',
//   t21: 'Knight armour',
//   t26: 'Bathrobe',
//   t29: 'Turtleneck jumper',
//   t22: 'Jumper',
//   t15: 'Tuxedo',
//   t68: 'Dollar chain',
//   t19: 'Navy jacket',
//   t20: 'Captain jacket',
//   t17: 'Military jacket',
//   t188: 'Mummy',
//   t30: 'Denim jacket',
//   t51: 'Dinner suit',
//   t157: 'Spiked armour',
//   t644: 'Straw top',
//   t72: 'Clock chain',
//   t406: 'Safari shirt',
//   t404: 'Caveman pelt',
//   t1013: 'Tribal tunic',
//   t158: 'Greek toga',
//   t401: 'Dog tags',
//   t43: 'Sports jacket',
//   t1012: 'Tribal armor',
//   t403: 'Claw mark t-shirt',
//   t24: 'Leather jacket',
//   t37: 'Bandolier',
//   t405: 'Lab jacket',
//   t712: 'Medieval armour',
//   t34: 'Striped t-shirt',
//   t410: 'Leaves',
//   t27: 'Straight jacket',
//   t35: 'Bulletproof vest',
//   t39: 'Hoodie',
//   t70: 'Police badge',
//   t38: 'Waistcoat',
//   t52: 'Puffer vest',
//   t402: 'Arrow quiver',
//   t31: 'Basketball jersey',
//   t47: 'High visibility vest',
//   t32: 'Dungarees',
//   t411: 'Tanktop',
//   t74: 'Bone necklace',
//   t41: 'Hawaiian shirt',
//   t407: 'Neckerchief',
//   t408: 'Dress',
//   t645: 'Fur waistcoat',
//   t44: 'Lumberjack shirt',
//   t42: 'FLAK vest',
//   t409: 'Camouflage t-shirt',
//   t23: 'Army jacket',
//   t36: 'Double sword holster',
//   t73: 'Silver chain',
//   t50: 'Body armor',
//   t28: 'Baseball jersey',
//   t69: 'Gold chain',
//   t25: 'Prison jumpsuit',
//   t76: 'Tongue out',
//   t83: 'Missing teeth',
//   t78: 'Rainbow teeth',
//   t79: 'Gold teeth',
//   t80: 'Silver teeth',
//   t380: 'Creepy',
//   t378: 'Toxic',
//   t383: 'Blood',
//   t75: 'Sewn mouth',
//   t77: 'Growl',
//   t162: 'Scary smile',
//   t82: 'Side smile',
//   t379: 'Zombie',
//   t381: 'Roar',
//   t385: 'Fangs',
//   t382: 'Shocked',
//   t384: 'Confused',
//   t161: 'Grin',
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t912: 'Odd',
//   t118: 'Orange hypnotised',
//   t71: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t911: 'Yellow',
//   t913: 'One eye closed',
//   t110: 'Bloodshot',
//   t112: 'Wide eyed',
//   t111: 'Green',
//   t108: 'Fire',
//   t114: 'Sleepy',
//   t115: 'Multicoloured',
//   t116: 'Cross',
//   t113: 'Black hypnotised',
//   t119: 'Red hypnotised',
//   t160: 'Plague',
//   t59: 'Hazard helmet',
//   t159: 'Oxygen mask',
//   t61: 'Guy Fawkes',
//   t54: 'Cyborg',
//   t62: 'Half skeleton',
//   t57: 'Half skull',
//   t60: 'Gas mask',
//   t63: 'Leather',
//   t634: 'Paw marks',
//   t100: 'Feather earring',
//   t102: 'Spiked earring',
//   t103: 'Earphones',
//   t101: 'Gold earring',
//   t104: 'Gold bar earring',
//   t105: 'Stud earrings',
//   t85: 'Robot eye',
//   t87: 'AR glasses',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t86: 'Bandage',
//   t89: 'Masquerade mask',
//   t93: 'Ski mask',
//   t96: 'Eyebrow ring',
//   t476: 'Eye glass',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t94: 'Eye patch',
//   t95: 'Reading glasses',
//   t98: 'Scar',
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//   t120: 'Crown',
//   t146: 'Nightvision helmet',
//   t121: 'Roman helmet',
//   t123: 'Soccer helmet',
//   t125: 'Boxing headgear',
//   t124: 'Viking helmet',
//   t152: 'Flat cap',
//   t127: 'Skating helmet',
//   t154: 'Mohawk',
//   t1011: 'Twill cap',
//   t126: 'Combat helmet',
//   t135: 'Trapper hat',
//   t137: 'Headphones',
//   t131: 'Bowler hat',
//   t129: 'Military hat',
//   t128: 'Sailors hat',
//   t145: 'Kaffiyeh',
//   t861: 'Wizards hat',
//   t862: 'Horns',
//   t133: 'Pirates hat',
//   t143: 'Turban',
//   t144: 'Hard hat',
//   t147: 'Roman leaf crown',
//   t122: 'Spike helmet',
//   t148: 'Fedora',
//   t654: 'Safari hat',
//   t655: 'Bamboo hat',
// };

//zebra
// export const names_list: any = {
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//   t1: 'Gold',
//   t2: 'Lava',
//   t165: 'Rainbow',
//   t163: 'Futuristic',
//   t164: 'Cheetah',
//   t4: 'Zombie',
//   t3: 'Robot',
//   t333: 'Pink',
//   t5: 'Cream',
//   t6: 'Red',
//   t7: 'Brown',
//   t166: 'Grey',
//   t8: 'Black',
//   t76: 'Tongue out',
//   t83: 'Missing teeth',
//   t78: 'Rainbow teeth',
//   t79: 'Gold teeth',
//   t80: 'Silver teeth',
//   t81: 'Goofy smile',
//   t161: 'Grin',
//   t162: 'Scary smile',
//   t75: 'Sewn mouth',
//   t82: 'Mouth open',
//   t77: 'Blowing',
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t109: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t111: 'Green',
//   t108: 'Fire',
//   t115: 'Multicoloured',
//   t116: 'Cross',
//   t119: 'Red hypnotised',
//   t112: 'Wide eyed',
//   t114: 'Sleepy',
//   t110: 'Bloodshot',
//   t113: 'Black hypnotised',
//   t160: 'Plague',
//   t58: 'Balaclava',
//   t159: 'Oxygen mask',
//   t54: 'Cyborg',
//   t62: 'Half skeleton',
//   t60: 'Gas mask',
//   t63: 'Leather',
//   t102: 'Spiked earring',
//   t100: 'Feather earring',
//   t101: 'Gold earring',
//   t103: 'Earphones',
//   t104: 'Gold bar earring',
//   t105: 'Stud earrings',
//   t85: 'Robot eye',
//   t87: 'AR glasses',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t86: 'Bandage',
//   t89: 'Masquerade mask',
//   t93: 'Ski mask',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t94: 'Eye patch',
//   t95: 'Reading glasses',
//   t98: 'Scar',
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//   t13: 'Jedi cape',
//   t71: 'Futuristic',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t53: 'Pilot jacket',
//   t26: 'Bathrobe',
//   t18: 'Fur coat',
//   t20: 'Captain jacket',
//   t22: 'Jumper',
//   t68: 'Dollar chain',
//   t188: 'Mummy',
//   t19: 'Navy jacket',
//   t17: 'Military jacket',
//   t33: 'Puffa jacket',
//   t15: 'Tuxedo',
//   t157: 'Spiked armour',
//   t51: 'Dinner suit',
//   t48: 'Shirt & sweater',
//   t50: 'Body armor',
//   t72: 'Clock chain',
//   t69: 'Gold chain',
//   t29: 'Turtleneck jumper',
//   t30: 'Denim jacket',
//   t70: 'Police badge',
//   t408: 'Dress',
//   t28: 'Baseball jersey',
//   t24: 'Leather jacket',
//   t43: 'Sports jacket',
//   t31: 'Basketball jersey',
//   t36: 'Double sword holster',
//   t37: 'Bandolier',
//   t42: 'FLAK vest',
//   t32: 'Dungarees',
//   t27: 'Straight jacket',
//   t158: 'Greek toga',
//   t47: 'High visibility vest',
//   t34: 'Striped t-shirt',
//   t23: 'Army jacket',
//   t52: 'Puffer vest',
//   t38: 'Waistcoat',
//   t35: 'Bulletproof vest',
//   t74: 'Bone necklace',
//   t44: 'Lumberjack shirt',
//   t73: 'Silver chain',
//   t25: 'Prison jumpsuit',
//   t39: 'Hoodie',
//   t41: 'Hawaiian shirt',
//   t402: 'Arrow quiver',
//   t913: 'Tribal tunic',
//   t912: 'Tribal armor',
//   t405: 'Lab jacket',
//   t410: 'Leaves',
//   t401: 'Dog tags',
//   t644: 'Straw top',
//   t406: 'Safari shirt',
//   t409: 'Camouflage t-shirt',
//   t645: 'Fur waistcoat',
//   t712: 'Medieval armour',
//   t411: 'Tanktop',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t403: 'Claw mark t-shirt',
//   t120: 'Crown',
//   t146: 'Nightvision helmet',
//   t121: 'Roman helmet',
//   t123: 'Soccer helmet',
//   t124: 'Viking helmet',
//   t125: 'Boxing headgear',
//   t152: 'Flat cap',
//   t127: 'Skating helmet',
//   t154: 'Mohawk',
//   t126: 'Combat helmet',
//   t911: 'Twill cap',
//   t135: 'Trapper hat',
//   t137: 'Tudor hat',
//   t131: 'Top hat',
//   t129: 'Military hat',
//   t138: 'Vizor hat',
//   t128: 'Sailors hat',
//   t140: 'Bush hat',
//   t145: 'Kaffiyeh',
//   t133: 'Pirates hat',
//   t143: 'Turban',
//   t144: 'Hard hat',
//   t141: 'Bandana',
//   t132: 'Cowboy hat',
//   t130: 'Straw hat',
//   t147: 'Roman leaf crown',
//   t122: 'Spike helmet',
//   t872: 'Beret',
//   t691: 'Metal helmet',
//   t139: 'Bucket hat',
//   t142: 'Baseball hat',
//   t136: 'Backwards hat',
//   t134: 'Bobble hat',
//   t148: 'Fedora',
//   t654: 'Safari hat',
//   t655: 'Bamboo hat',
//   t961: 'NEED NAME FOR THIS TRAIT',
// };

export const getTraitName = (name: string) => {
  if (names_list[name]) {
    return names_list[name];
  }
  console.log('ERROR NOT FOUND NAME: ' + name);
  return '';
};
