const names_list = {
  // Background
  b1: "Gold",
  b2: "Red",
  b3: "Blue",
  b4: "Pink",
  b5: "Purple",
  b6: "Green",
  b7: "Aqua",
  b8: "Grey",
  // Fur
  t1: "Gold",
  t2: "Lava",
  t163: "Futuristic",
  t164: "Cheetah",
  t165: "Rainbow",
  t3: "Robot",
  t4: "Zombie",
  t5: "Cream",
  t6: "Red",
  t7: "Grey",
  t8: "Brown",
  t166: "Dark brown",
  t333: "Pink",
  // Clothes
  t13: "Jedi cape",
  t16: "Robot claws",
  t14: "Futuristic",
  t21: "Knight armour",
  t45: "Smoking jacket",
  t26: "Bathrobe",
  t18: "Fur coat",
  t53: "Pilot jacket",
  t20: "Captain jacket",
  t22: "Jumper",
  t17: "Military jacket",
  t188: "Mummy",
  t19: "Navy jacket",
  t157: "Spiked armour",
  t158: "Greek toga",
  t50: "Body armor",
  t41: "Hawaiian shirt",
  t42: "FLAK vest",
  t37: "Bandolier",
  t36: "Double sword holster",
  t15: "Tuxedo",
  t33: "Puffa jacket",
  t38: "Waistcoat",
  t51: "Dinner suit",
  t48: "Shirt & sweater",
  t23: "Army jacket",
  t34: "Striped t-shirt",
  t27: "Straight jacket",
  t28: "Baseball jersey",
  t29: "Turtleneck jumper",
  t30: "Denim jacket",
  t31: "Basketball jersey",
  t32: "Dungarees",
  t25: "Prison jumpsuit",
  t35: "Bulletproof vest",
  t52: "Puffer vest",
  t47: "High visibility vest",
  t24: "Leather jacket",
  t44: "Lumberjack shirt",
  t46: "Ripped t-shirt",
  t43: "Sports jacket",
  t39: "Hoodie",
  t40: "T-Shirt",
  // Mouth
  t76: "Tongue out",
  t82: "Missing teeth",
  t78: "Rainbow teeth",
  t79: "Gold teeth",
  t80: "Silver teeth",
  t81: "Goofy smile",
  t161: "Grin",
  t162: "Scary smile",
  t75: "Sewn mouth",
  t83: "Side smile",
  t77: "Blowing",
  empty: "Frown",
  // Neck wear
  t68: "Dollar chain",
  t69: "Gold chain",
  t70: "Police badge",
  t71: "Neck bolts",
  t72: "Clock chain",
  t73: "Silver chain",
  t74: "Bone necklace",
  // masks
  t160: "Plague",
  t59: "Hazard helmet",
  t64: "Clown",
  t65: "Horror",
  t55: "Robot",
  t56: "Machine",
  t58: "Balaclava",
  t159: "Oxygen mask",
  t61: "Guy Fawkes",
  t54: "Cyborg",
  t62: "Half skeleton",
  t57: "Half skull",
  t60: "Gas mask",
  t63: "Leather",
  // nose
  t66: "Nose bar",
  t67: "Nose ring",
  // ear wear
  t102: "Stretched earring",
  t100: "Feather earring",
  t101: "Gold earring",
  t103: "Earphones",
  t104: "Silver bar earring",
  t105: "Stud earrings",
  // eye wear
  t85: "Futuristic glasses",
  t87: "AR glasses",
  t97: "Eyebrow bar",
  t99: "3D glasses",
  t86: "Bandage",
  t89: "Masquerade mask",
  t93: "Ski mask",
  t96: "Eyebrow ring",
  t84: "Cyborg eye",
  t88: "Disco glasses",
  t90: "Bandit mask",
  t91: "Aviator glasses",
  t92: "Goggles",
  t94: "Eye patch",
  t95: "Reading glasses",
  t98: "Scar",
  // head
  t120: "Crown",
  t121: "Roman helmet",
  t122: "Spike helmet",
  t123: "Soccer helmet",
  t124: "Viking helmet",
  t125: "Boxing headgear",
  t126: "Top hat",
  t127: "Skating helmet",
  t128: "Sailors hat",
  t129: "Military hat",
  t130: "Straw hat",
  t131: "Bowler hat",
  t132: "Cowboy hat",
  t133: "Pirates hat",
  t134: "Bobble hat",
  t135: "Trapper hat",
  t136: "Backwards hat",
  t137: "Headphones",
  t138: "Vizor hat",
  t139: "Bucket hat",
  t140: "Beenie hat",
  t141: "Bandana",
  t142: "Baseball hat",
  t143: "Turban",
  t144: "Beret",
  t145: "Hard hat",
  t146: "Nightvision helmet",
  t147: "Roman leaf crown",
  t148: "Long hair",
  t149: "Quiff hair",
  t150: "Afro hair",
  t151: "Punk hair",
  t152: "Dreadlocks",
  t153: "Man bun",
  t154: "Mohawk",
  t155: "Braided hair",
  // eyes
  t106: "Eyeball out",
  t107: "One eye",
  t118: "Orange hypnotised",
  t109: "Futuristic",
  t117: "Blue hypnotised",
  t111: "Green",
  t108: "Fire",
  t115: "Multicoloured",
  t116: "Cross",
  t119: "Red hypnotised",
  t112: "Wide eyed",
  t114: "Sleepy",
  t110: "Bloodshot",
  t113: "Black hypnotised",
  // new
  t408: "Dress",
  t402: "Arrow quiver",
  t405: "Lab jacket",
  t410: "Leaves",
  t401: "Dog tags",
  t406: "Safari shirt",
  t409: "Camouflage t-shirt",
  t411: "Tanktop",
  t407: "Neckerchief",
  t404: "Caveman pelt",
  t403: "Claw mark t-shirt",

  t655: "Bamboo hat",
  t654: "Safari hat",
  t656: "Bone",

}

const getTraitName = (name) => {
  if (names_list[name]) {
    return names_list[name];
  }
  console.log("ERROR NOT FOUND NAME: " + name)
  return "";
};

const getTraitByName = (name, trait_type) => {
  for (const namesListKey in names_list) {
    if (names_list[namesListKey] === name)

      if (!(trait_type !== 'Background' && namesListKey[0] === 'b')) {
        return namesListKey;
      }

  }
}

module.exports = {
  getTraitName,
  getTraitByName
};
