//monkey
// export const names_list: any = {
//   // Background
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//   // Fur
//   t1: 'Gold',
//   t2: 'Lava',
//   t163: 'Futuristic',
//   t164: 'Cheetah',
//   t165: 'Rainbow',
//   t3: 'Robot',
//   t4: 'Zombie',
//   t5: 'Cream',
//   t6: 'Red',
//   t7: 'Grey',
//   t8: 'Brown',
//   t166: 'Dark brown',
//   t333: 'Pink',
//   // Clothes
//   t13: 'Jedi cape',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t26: 'Bathrobe',
//   t18: 'Fur coat',
//   t53: 'Pilot jacket',
//   t20: 'Captain jacket',
//   t22: 'Jumper',
//   t17: 'Military jacket',
//   t188: 'Mummy',
//   t19: 'Navy jacket',
//   t157: 'Spiked armour',
//   t158: 'Greek toga',
//   t50: 'Body armor',
//   t41: 'Hawaiian shirt',
//   t42: 'FLAK vest',
//   t37: 'Bandolier',
//   t36: 'Double sword holster',
//   t15: 'Tuxedo',
//   t33: 'Puffa jacket',
//   t38: 'Waistcoat',
//   t51: 'Dinner suit',
//   t48: 'Shirt & sweater',
//   t23: 'Army jacket',
//   t34: 'Striped t-shirt',
//   t27: 'Straight jacket',
//   t28: 'Baseball jersey',
//   t29: 'Turtleneck jumper',
//   t30: 'Denim jacket',
//   t31: 'Basketball jersey',
//   t32: 'Dungarees',
//   t25: 'Prison jumpsuit',
//   t35: 'Bulletproof vest',
//   t52: 'Puffer vest',
//   t47: 'High visibility vest',
//   t24: 'Leather jacket',
//   t44: 'Lumberjack shirt',
//   t46: 'Ripped t-shirt',
//   t43: 'Sports jacket',
//   t39: 'Hoodie',
//   t40: 'T-Shirt',
//   // Mouth
//   t76: 'Tongue out',
//   t82: 'Missing teeth',
//   t78: 'Rainbow teeth',
//   t79: 'Gold teeth',
//   t80: 'Silver teeth',
//   t81: 'Goofy smile',
//   t161: 'Grin',
//   t162: 'Scary smile',
//   t75: 'Sewn mouth',
//   t83: 'Side smile',
//   t77: 'Blowing',
//   empty: 'Frown',
//   // Neck wear
//   t68: 'Dollar chain',
//   t69: 'Gold chain',
//   t70: 'Police badge',
//   t71: 'Neck bolts',
//   t72: 'Clock chain',
//   t73: 'Silver chain',
//   t74: 'Bone necklace',
//   // masks
//   t160: 'Plague',
//   t59: 'Hazard helmet',
//   t64: 'Clown',
//   t65: 'Horror',
//   t55: 'Robot',
//   t56: 'Machine',
//   t58: 'Balaclava',
//   t159: 'Oxygen mask',
//   t61: 'Guy Fawkes',
//   t54: 'Cyborg',
//   t62: 'Half skeleton',
//   t57: 'Half skull',
//   t60: 'Gas mask',
//   t63: 'Leather',
//   // nose
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   // ear wear
//   t102: 'Stretched earring',
//   t100: 'Feather earring',
//   t101: 'Gold earring',
//   t103: 'Earphones',
//   t104: 'Silver bar earring',
//   t105: 'Stud earrings',
//   // eye wear
//   t85: 'Futuristic glasses',
//   t87: 'AR glasses',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t86: 'Bandage',
//   t89: 'Masquerade mask',
//   t93: 'Ski mask',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t94: 'Eye patch',
//   t95: 'Reading glasses',
//   t98: 'Scar',
//   // head
//   t120: 'Crown',
//   t121: 'Roman helmet',
//   t122: 'Spike helmet',
//   t123: 'Soccer helmet',
//   t124: 'Viking helmet',
//   t125: 'Boxing headgear',
//   t126: 'Top hat',
//   t127: 'Skating helmet',
//   t128: 'Sailors hat',
//   t129: 'Military hat',
//   t130: 'Straw hat',
//   t131: 'Bowler hat',
//   t132: 'Cowboy hat',
//   t133: 'Pirates hat',
//   t134: 'Bobble hat',
//   t135: 'Trapper hat',
//   t136: 'Backwards hat',
//   t137: 'Headphones',
//   t138: 'Vizor hat',
//   t139: 'Bucket hat',
//   t140: 'Beenie hat',
//   t141: 'Bandana',
//   t142: 'Baseball hat',
//   t143: 'Turban',
//   t144: 'Beret',
//   t145: 'Hard hat',
//   t146: 'Nightvision helmet',
//   t147: 'Roman leaf crown',
//   t148: 'Long hair',
//   t149: 'Quiff hair',
//   t150: 'Afro hair',
//   t151: 'Punk hair',
//   t152: 'Dreadlocks',
//   t153: 'Man bun',
//   t154: 'Mohawk',
//   t155: 'Braided hair',
//   // eyes
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t109: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t111: 'Green',
//   t108: 'Fire',
//   t115: 'Multicoloured',
//   t116: 'Cross',
//   t119: 'Red hypnotised',
//   t112: 'Wide eyed',
//   t114: 'Sleepy',
//   t110: 'Bloodshot',
//   t113: 'Black hypnotised',
//   // new
//   t408: 'Dress',
//   t402: 'Arrow quiver',
//   t405: 'Lab jacket',
//   t410: 'Leaves',
//   t401: 'Dog tags',
//   t406: 'Safari shirt',
//   t409: 'Camouflage t-shirt',
//   t411: 'Tanktop',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t403: 'Claw mark t-shirt',
//
//   t655: 'Bamboo hat',
//   t654: 'Safari hat',
//   t656: 'Bone',
// };

//panda
// export const names_list: any = {
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//
//   t165: 'Rainbow',
//   t2: 'Lava',
//   t164: 'Cheetah',
//   t163: 'Futuristic',
//   t1: 'Gold',
//   t333: 'Pink',
//   t3: 'Robot',
//   t5: 'Cream',
//   t4: 'Zombie',
//   t8: 'Black',
//   t7: 'Striped',
//   t166: 'Grey',
//   t6: 'Red',
//
//   t13: 'Jedi cape',
//   t53: 'Pilot jacket',
//   t45: 'Smoking jacket',
//   t26: 'Bathrobe',
//   t20: 'Captain jacket',
//   t18: 'Fur coat',
//   t21: 'Knight armour',
//   t22: 'Jumper',
//   t16: 'Robot claws',
//   t71: 'Futuristic',
//   t51: 'Dinner suit',
//   t17: 'Military jacket',
//   t50: 'Body armor',
//   t68: 'Dollar chain',
//   t157: 'Spiked armour',
//   t48: 'Shirt & sweater',
//   t19: 'Navy jacket',
//   t15: 'Tuxedo',
//   t33: 'Puffa jacket',
//   t188: 'Mummy',
//   t405: 'Lab jacket',
//   t402: 'Arrow quiver',
//   t401: 'Dog tags',
//   t34: 'Striped t-shirt',
//   t39: 'Hoodie',
//   t38: 'Waistcoat',
//   t28: 'Baseball jersey',
//   t404: 'Caveman pelt',
//   t24: 'Leather jacket',
//   t52: 'Puffer vest',
//   t41: 'Hawaiian shirt',
//   t74: 'Bone necklace',
//   t27: 'Straight jacket',
//   t403: 'Claw mark t-shirt',
//   t29: 'Turtleneck jumper',
//   t43: 'Sports jacket',
//   t73: 'Silver chain',
//   t25: 'Prison jumpsuit',
//   t42: 'FLAK vest',
//   t35: 'Bulletproof vest',
//   t411: 'Tanktop',
//   t409: 'Camouflage t-shirt',
//   t406: 'Safari shirt',
//   t72: 'Clock chain',
//   t410: 'Leaves',
//   t69: 'Gold chain',
//   t37: 'Bandolier',
//   t407: 'Neckerchief',
//   t158: 'Greek toga',
//   t44: 'Lumberjack shirt',
//   t31: 'Basketball jersey',
//   t23: 'Army jacket',
//   t32: 'Dungarees',
//   t36: 'Double sword holster',
//   t70: 'Police badge',
//   t47: 'High visibility vest',
//   t30: 'Denim jacket',
//   t408: 'Dress',
//
//   t78: 'Rainbow teeth',
//   t80: 'Silver teeth',
//   t79: 'Gold teeth',
//   t76: 'Tongue out',
//   t82: 'Missing teeth',
//   t75: 'Sewn mouth',
//   t161: 'Grin',
//   t81: 'Goofy smile',
//   t162: 'Scary smile',
//   t77: 'Blowing',
//   t83: 'Side smile',
//
//   t111: 'Green',
//   t118: 'Orange hypnotised',
//   t117: 'Blue hypnotised',
//   t363: 'Futuristic',
//   t107: 'One eye',
//   t106: 'Eyeball out',
//   t108: 'Fire',
//   t116: 'Cross',
//   t115: 'Multicoloured',
//   t112: 'Wide eyed',
//   t119: 'Red hypnotised',
//   t114: 'Sleepy',
//   t110: 'Bloodshot',
//   t113: 'Black hypnotised',
//
//   t160: 'Plague',
//   t60: 'Gas mask',
//   t159: 'Oxygen mask',
//   t54: 'Cyborg',
//   t62: 'Half skeleton',
//   t65: 'Horror',
//   t303: 'Machine',
//   t56: 'Jigsaw',
//   t58: 'Balaclava',
//   t63: 'Leather',
//   t64: 'Clown',
//   t59: 'Hazard helmet',
//   t61: 'Guy Fawkes',
//   t57: 'Half skull',
//
//   t101: 'Gold earring',
//   t102: 'Spiked earring',
//   t100: 'Feather earring',
//   t105: 'Stud earrings',
//   t104: 'Silver bar earring',
//   t103: 'Earphones',
//
//   t87: 'AR glasses',
//   t86: 'Bandage',
//   t89: 'Masquerade mask',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t85: 'Robot eye',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t93: 'Ski mask',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t98: 'Scar',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t95: 'Reading glasses',
//   t94: 'Eye patch',
//
//   t67: 'Nose ring',
//   t66: 'Nose bar',
//   t656: 'Bone',
//
//
//   t126: 'Top hat',
//   t151: 'Punk hair',
//   t154: 'Mohawk',
//   t121: 'Roman helmet',
//   t124: 'Viking helmet',
//   t146: 'Nightvision helmet',
//   t152: 'Dreadlocks',
//   t120: 'Crown',
//   t125: 'Boxing headgear',
//   t123: 'Soccer helmet',
//   t145: 'Hard hat',
//   t138: 'Kaffiyeh',
//   t140: 'Beenie hat',
//   t144: 'Beret',
//   t127: 'Skating helmet',
//   t148: 'Long hair',
//   t122: 'Spike helmet',
//   t131: 'Bowler hat',
//   t143: 'Turban',
//   t153: 'Man bun',
//   t137: 'Headphones',
//   t134: 'Bobble hat',
//   t139: 'Bucket hat',
//   t141: 'Bandana',
//   t142: 'Baseball hat',
//   t654: 'Safari hat',
//   t130: 'Straw hat',
//   t128: 'Sailors hat',
//   t147: 'Roman leaf crown',
//   t135: 'Trapper hat',
//   t655: 'Bamboo hat',
//   t129: 'Military hat',
//   t132: 'Cowboy hat',
//   t136: 'Backwards hat',
//   t133: 'Pirates hat',
// };

// hyena
// export const names_list: any = {
//   // Background
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//   // Fur
//   t1: 'Gold',
//   t2: 'Lava',
//   t165: 'Rainbow',
//   t163: 'Futuristic',
//   t164: 'Grey',
//   t4: 'Zombie',
//   t3: 'Robot',
//   t333: 'Pink',
//   t5: 'Cream',
//   t6: 'Red',
//   t7: 'Striped',
//   t166: 'Light brown',
//   t8: 'Beige',
//
//   t76: 'Tongue out',
//   t83: 'Side smile',
//   t78: 'Rainbow teeth',
//   t79: 'Gold teeth',
//   t80: 'Silver teeth',
//   t81: 'Goofy smile',
//   t161: 'Grin',
//   t162: 'Scary smile',
//   t75: 'Sewn mouth',
//   t82: 'Mouth open',
//   t77: 'Blowing',
//
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t109: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t111: 'Green',
//   t108: 'Fire',
//   t115: 'Multicoloured',
//   t116: 'Cross',
//   t119: 'Red hypnotised',
//   t112: 'Wide eyed',
//   t114: 'Sleepy',
//   t110: 'Bloodshot',
//   t113: 'Black hypnotised',
//
//   t160: 'Plague',
//   t59: 'Hazard helmet',
//   t64: 'Clown',
//   t65: 'Horror',
//   t55: 'Robot',
//   t56: 'Jigsaw',
//   t58: 'Balaclava',
//   t159: 'Oxygen mask',
//   t61: 'Guy Fawkes',
//   t54: 'Cyborg',
//   t62: 'Half skeleton',
//   t57: 'Half skull',
//   t60: 'Gas mask',
//   t63: 'Leather',
//
//   t102: 'Spiked earring',
//   t100: 'Feather earring',
//   t101: 'Gold earring',
//   t103: 'Earphones',
//   t104: 'Silver bar earring',
//   t105: 'Stud earrings',
//
//   t85: 'Robot eye',
//   t87: 'AR glasses',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t86: 'Bandage',
//   t89: 'Masquerade mask',
//   t93: 'Ski mask',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t94: 'Eye patch',
//   t95: 'Reading glasses',
//   t98: 'Scar',
//
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//
//   t13: 'Jedi cape',
//   t71: 'Neck bolts',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t53: 'Pilot jacket',
//   t26: 'Bathrobe',
//   t18: 'Fur coat',
//   t20: 'Captain jacket',
//   t22: 'Jumper',
//   t68: 'Dollar chain',
//   t188: 'Mummy',
//   t19: 'Navy jacket',
//   t17: 'Military jacket',
//   t33: 'Puffa jacket',
//   t15: 'Tuxedo',
//   t157: 'Spiked armour',
//   t51: 'Dinner suit',
//   t48: 'Shirt & sweater',
//   t50: 'Body armor',
//   t72: 'Clock chain',
//   t69: 'Gold chain',
//   t29: 'Turtleneck jumper',
//   t30: 'Denim jacket',
//   t70: 'Police badge',
//   t408: 'Dress',
//   t28: 'Baseball jersey',
//   t24: 'Leather jacket',
//   t43: 'Sports jacket',
//   t31: 'Basketball jersey',
//   t36: 'Double sword holster',
//   t37: 'Bandolier',
//   t42: 'FLAK vest',
//   t32: 'Dungarees',
//   t27: 'Straight jacket',
//   t158: 'Greek toga',
//   t47: 'High visibility vest',
//   t34: 'Striped t-shirt',
//   t23: 'Army jacket',
//   t52: 'Puffer vest',
//   t38: 'Waistcoat',
//   t35: 'Bulletproof vest',
//   t74: 'Bone necklace',
//   t44: 'Lumberjack shirt',
//   t73: 'Silver chain',
//   t25: 'Prison jumpsuit',
//   t39: 'Hoodie',
//   t41: 'Hawaiian shirt',
//   t402: 'Arrow quiver',
//   t405: 'Lab jacket',
//   t410: 'Leaves',
//   t401: 'Dog tags',
//   t406: 'Safari shirt',
//   t409: 'Camouflage t-shirt',
//   t411: 'Tanktop',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t403: 'Claw mark t-shirt',
//
//   t120: 'Crown',
//   t146: 'Nightvision helmet',
//   t121: 'Roman helmet',
//   t123: 'Soccer helmet',
//   t124: 'Viking helmet',
//   t125: 'Boxing headgear',
//   t152: 'Dreadlocks',
//   t127: 'Skating helmet',
//   t154: 'Mohawk',
//   t126: 'Combat helmet',
//   t151: 'Punk hair',
//   t135: 'Trapper hat',
//   t153: 'Man bun',
//   t137: 'Headphones',
//   t131: 'Bowler hat',
//   t129: 'Military hat',
//   t138: 'Vizor hat',
//   t128: 'Sailors hat',
//   t140: 'Beenie hat',
//   t145: 'Flat cap',
//   t133: 'Pirates hat',
//   t143: 'Turban',
//   t148: 'Long hair',
//   t144: 'Beret',
//   t141: 'Bandana',
//   t132: 'Cowboy hat',
//   t130: 'Straw hat',
//   t147: 'Roman leaf crown',
//   t122: 'Spike helmet',
//   t139: 'Bucket hat',
//   t142: 'Baseball hat',
//   t136: 'Backwards hat',
//   t134: 'Bobble hat',
//   t654: 'Safari hat',
//   t655: 'Bamboo hat',
//   empty: 'empty',
// };
// cheetah
// export const names_list: any = {
//   b1:'Gold',
//   b2:'Red',
//   b3:'Blue',
//   b4:'Pink',
//   b5:'Purple',
//   b6:'Green',
//   b7:'Aqua',
//   b8:'Grey',
//
//   t1:'Gold',
//   t2:'Lava',
//   t165:'Rainbow',
//   t163:'Futuristic',
//   t164:'Striped',
//   t4:'Zombie',
//   t3:'Robot',
//   t333:'Pink',
//   t5:'Cream',
//   t6:'Red',
//   t7:'Grey',
//   t166:'Dark brown',
//   t8:'Light brown',
//
//   t76:'Tongue out',
//   t83:'Missing teeth',
//   t78:'Rainbow teeth',
//   t79:'Gold teeth',
//   t80:'Silver teeth',
//   t81:'Mouth open',
//   t161:'Grin',
//   t162:'Scary smile',
//   t75:'Sewn mouth',
//   t82:'Side smile',
//   t77:'Blowing',
//
//   t106:'Eyeball out',
//   t107:'One eye',
//   t118:'Orange hypnotised',
//   t109:'Futuristic',
//   t117:'Blue hypnotised',
//   t111:'Green',
//   t108:'Fire',
//   t115:'Multicoloured',
//   t116:'Cross',
//   t119:'Red hypnotised',
//   t112:'Wide eyed',
//   t114:'Sleepy',
//   t110:'Bloodshot',
//   t113:'Black hypnotised',
//
//   t160:'Plague',
//   t59:'Hazard helmet',
//   t64:'Clown',
//   t65:'Horror',
//   t55:'Robot',
//   t56:'Jigsaw',
//   t58:'Balaclava',
//   t159:'Oxygen mask',
//   t61:'Guy Fawkes',
//   t54:'Cyborg',
//   t62:'Half skeleton',
//   t57:'Half skull',
//   t60:'Gas mask',
//   t63:'Leather',
//
//   t102:'Spiked earring',
//   t100:'Feather earring',
//   t101:'Gold earring',
//   t103:'Earphones',
//   t104:'Silver bar earring',
//   t105:'Stud earrings',
//
//   t85:'Robot eye',
//   t87:'AR glasses',
//   t97:'Eyebrow bar',
//   t99:'3D glasses',
//   t86:'Bandage',
//   t89:'Masquerade mask',
//   t93:'Ski mask',
//   t96:'Eyebrow ring',
//   t84:'Cyborg eye',
//   t88:'Disco glasses',
//   t90:'Bandit mask',
//   t91:'Aviator glasses',
//   t92:'Goggles',
//   t94:'Eye patch',
//   t95:'Reading glasses',
//   t98:'Scar',
//
//   t66:'Nose bar',
//   t67:'Nose ring',
//   t656:'Bone',
//
//   t13:'Jedi cape',
//   t71:'Futuristic',
//   t16:'Robot claws',
//   t21:'Knight armour',
//   t45:'Smoking jacket',
//   t53:'Pilot jacket',
//   t26:'Bathrobe',
//   t18:'Fur coat',
//   t20:'Captain jacket',
//   t22:'Jumper',
//   t68:'Dollar chain',
//   t188:'Mummy',
//   t19:'Navy jacket',
//   t17:'Military jacket',
//   t33:'Puffa jacket',
//   t15:'Tuxedo',
//   t157:'Spiked armour',
//   t51:'Dinner suit',
//   t48:'Shirt & sweater',
//   t50:'Body armor',
//   t72:'Clock chain',
//   t69:'Gold chain',
//   t29:'Turtleneck jumper',
//   t30:'Denim jacket',
//   t70:'Police badge',
//   t408:'Dress',
//   t28:'Baseball jersey',
//   t24:'Leather jacket',
//   t43:'Sports jacket',
//   t31:'Basketball jersey',
//   t36:'Double sword holster',
//   t37:'Bandolier',
//   t42:'FLAK vest',
//   t32:'Dungarees',
//   t27:'Straight jacket',
//   t158:'Greek toga',
//   t47:'High visibility vest',
//   t34:'Striped t-shirt',
//   t23:'Army jacket',
//   t52:'Puffer vest',
//   t38:'Waistcoat',
//   t35:'Bulletproof vest',
//   t74:'Bone necklace',
//   t44:'Lumberjack shirt',
//   t73:'Silver chain',
//   t25:'Prison jumpsuit',
//   t39:'Hoodie',
//   t41:'Hawaiian shirt',
//   t402:'Arrow quiver',
//   t405:'Lab jacket',
//   t410:'Leaves',
//   t401:'Dog tags',
//   t406:'Safari shirt',
//   t409:'Camouflage t-shirt',
//   t411:'Tanktop',
//   t407:'Neckerchief',
//   t404:'Caveman pelt',
//   t403:'Claw mark t-shirt',
//
//   t120:'Crown',
//   t146:'Nightvision helmet',
//   t121:'Flat cap',
//   t123:'Soccer helmet',
//   t124:'Viking helmet',
//   t125:'Boxing headgear',
//   t152:'Dreadlocks',
//   t127:'Skating helmet',
//   t154:'Mohawk',
//   t126:'Beret',
//   t151:'Punk hair',
//   t135:'Trapper hat',
//   t153:'Man bun',
//   t137:'Headphones',
//   t131:'Bowler hat',
//   t129:'Military hat',
//   t138:'Vizor hat',
//   t128:'Sailors hat',
//   t140:'Beenie hat',
//   t145:'Kaffiyeh',
//   t133:'Pirates hat',
//   t143:'Turban',
//   t148:'Long hair',
//   t144:'Hard hat',
//   t141:'Bandana',
//   t132:'Cowboy hat',
//   t130:'Straw hat',
//   t147:'Roman leaf crown',
//   t122:'Spike helmet',
//   t139:'Bucket hat',
//   t142:'Baseball hat',
//   t136:'Backwards hat',
//   t134:'Bobble hat',
//   t654:'Safari hat',
//   t655:'Bamboo hat',
// }

// koala
// export const names_list: any = {
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//
//   t1: 'Gold',
//   t2: 'Lava',
//   t165: 'Rainbow',
//   t163: 'Futuristic',
//   t164: 'Cheetah',
//   t4: 'Zombie',
//   t3: 'Robot',
//   t333: 'Pink',
//   t5: 'Cream',
//   t6: 'Red',
//   t7: 'Striped',
//   t166: 'Dark grey',
//   t8: 'Grey',
//
//   t76: 'Tongue out',
//   t83: 'Missing teeth',
//   t78: 'Rainbow teeth',
//   t79: 'Gold teeth',
//   t80: 'Silver teeth',
//   t81: 'Goofy smile',
//   t161: 'Grin',
//   t162: 'Scary smile',
//   t75: 'Sewn mouth',
//   t82: 'Side smile',
//   t77: 'Blowing',
//
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t109: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t111: 'Green',
//   t108: 'Fire',
//   t115: 'Multicoloured',
//   t116: 'Cross',
//   t119: 'Red hypnotised',
//   t112: 'Wide eyed',
//   t114: 'Sleepy',
//   t110: 'Bloodshot',
//   t113: 'Black hypnotised',
//
//   t160: 'Plague',
//   t59: 'Hazard helmet',
//   t64: 'Clown',
//   t65: 'Machine',
//   t55: 'Robot',
//   t56: 'Jigsaw',
//   t58: 'Balaclava',
//   t159: 'Oxygen mask',
//   t61: 'Guy Fawkes',
//   t54: 'Cyborg',
//   t62: 'Half skeleton',
//   t57: 'Half skull',
//   t60: 'Gas mask',
//   t63: 'Leather',
//
//   t102: 'Spiked earring',
//   t100: 'Feather earring',
//   t101: 'Gold earring',
//   t103: 'Earphones',
//   t104: 'Silver bar earring',
//   t105: 'Stud earrings',
//
//   t85: 'Robot eye',
//   t87: 'AR glasses',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t86: 'Bandage',
//   t89: 'Masquerade mask',
//   t93: 'Ski mask',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t94: 'Eye patch',
//   t95: 'Reading glasses',
//   t98: 'Scar',
//
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//
//   t13: 'Jedi cape',
//   t71: 'Neck bolts',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t53: 'Pilot jacket',
//   t26: 'Bathrobe',
//   t18: 'Fur coat',
//   t20: 'Captain jacket',
//   t22: 'Jumper',
//   t68: 'Dollar chain',
//   t188: 'Mummy',
//   t19: 'Navy jacket',
//   t17: 'Military jacket',
//   t33: 'Puffa jacket',
//   t15: 'Tuxedo',
//   t157: 'Spiked armour',
//   t51: 'Dinner suit',
//   t48: 'Shirt & sweater',
//   t50: 'Body armor',
//   t72: 'Clock chain',
//   t69: 'Gold chain',
//   t29: 'Turtleneck jumper',
//   t30: 'Denim jacket',
//   t70: 'Police badge',
//   t408: 'Dress',
//   t28: 'Baseball jersey',
//   t24: 'Leather jacket',
//   t43: 'Sports jacket',
//   t31: 'Basketball jersey',
//   t36: 'Double sword holster',
//   t37: 'Bandolier',
//   t42: 'FLAK vest',
//   t32: 'Dungarees',
//   t27: 'Straight jacket',
//   t158: 'Greek toga',
//   t47: 'High visibility vest',
//   t34: 'Striped t-shirt',
//   t23: 'Army jacket',
//   t52: 'Puffer vest',
//   t38: 'Waistcoat',
//   t35: 'Bulletproof vest',
//   t74: 'Bone necklace',
//   t44: 'Lumberjack shirt',
//   t73: 'Silver chain',
//   t25: 'Prison jumpsuit',
//   t39: 'Hoodie',
//   t41: 'Hawaiian shirt',
//   t402: 'Arrow quiver',
//   t405: 'Lab jacket',
//   t410: 'Leaves',
//   t401: 'Dog tags',
//   t406: 'Safari shirt',
//   t409: 'Camouflage t-shirt',
//   t411: 'Tanktop',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t403: 'Claw mark t-shirt',
//
//   t120: 'Crown',
//   t146: 'Nightvision helmet',
//   t121: 'Roman helmet',
//   t123: 'Soccer helmet',
//   t124: 'Viking helmet',
//   t125: 'Boxing headgear',
//   t152: 'Dreadlocks',
//   t127: 'Skating helmet',
//   t154: 'Mohawk',
//   t126: 'Combat helmet',
//   t151: 'Punk hair',
//   t135: 'Trapper hat',
//   t153: 'Man bun',
//   t137: 'Headphones',
//   t131: 'Bowler hat',
//   t129: 'Military hat',
//   t138: 'Vizor hat',
//   t128: 'Sailors hat',
//   t140: 'Beenie hat',
//   t145: 'Kaffiyeh',
//   t133: 'Pirates hat',
//   t143: 'Turban',
//   t148: 'Long hair',
//   t144: 'Beret',
//   t141: 'Bandana',
//   t132: 'Cowboy hat',
//   t130: 'Straw hat',
//   t147: 'Roman leaf crown',
//   t122: 'Spike helmet',
//   t139: 'Bucket hat',
//   t142: 'Baseball hat',
//   t136: 'Backwards hat',
//   t134: 'Bobble hat',
//   t654: 'Safari hat',
//   t655: 'Bamboo hat',
// };

// elephant
// export const names_list: any = {
//   id: 'Background',
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//
//   t1: 'Gold',
//   t2: 'Lava',
//   t165: 'Rainbow',
//   t163: 'Futuristic',
//   t164: 'Cheetah',
//   t4: 'Zombie',
//   t3: 'Robot',
//   t333: 'Pink',
//   t5: 'Cream',
//   t6: 'Red',
//   t7: 'Striped',
//   t166: 'Dark grey',
//   t8: 'Grey',
//   t76: 'Tongue out',
//   t83: 'Missing teeth',
//   t78: 'Rainbow teeth',
//   t79: 'Gold teeth',
//   t80: 'Silver teeth',
//   t81: 'Mouth open',
//   t161: 'Grin',
//   t162: 'Scary smile',
//   t75: 'Sewn mouth',
//   t82: 'Side smile',
//   t77: 'Blowing',
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t109: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t111: 'Green',
//   t108: 'Fire',
//   t115: 'Multicoloured',
//   t116: 'Cross',
//   t119: 'Red hypnotised',
//   t112: 'Wide eyed',
//   t114: 'Sleepy',
//   t110: 'Bloodshot',
//   t113: 'Black hypnotised',
//   t160: 'Plague',
//   t59: 'Hazard helmet',
//   t64: 'Clown',
//   t65: 'Horror',
//   t55: 'Robot',
//   t56: 'Jigsaw',
//   t58: 'Balaclava',
//   t159: 'Machine',
//   t61: 'Guy Fawkes',
//   t54: 'Cyborg',
//   t62: 'Half skeleton',
//   t57: 'Half skull',
//   t60: 'Gas mask',
//   t63: 'Leather',
//   t102: 'Spiked earring',
//   t100: 'Feather earring',
//   t101: 'Gold earring',
//   t103: 'Earphones',
//   t104: 'Gold bar earring',
//   t105: 'Stud earrings',
//   t85: 'Robot eye',
//   t87: 'AR glasses',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t86: 'Bandage',
//   t89: 'Sunglasses',
//   t93: 'Ski mask',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t94: 'Eye patch',
//   t95: 'Reading glasses',
//   t98: 'Scar',
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//   t13: 'Jedi cape',
//   t71: 'Futuristic',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t53: 'Pilot jacket',
//   t26: 'Bathrobe',
//   t18: 'Fur coat',
//   t20: 'Captain jacket',
//   t22: 'Jumper',
//   t68: 'Dollar chain',
//   t188: 'Mummy',
//   t19: 'Navy jacket',
//   t17: 'Military jacket',
//   t33: 'Puffa jacket',
//   t15: 'Tuxedo',
//   t157: 'Spiked armour',
//   t51: 'Dinner suit',
//   t48: 'Shirt & sweater',
//   t50: 'Body armor',
//   t72: 'Clock chain',
//   t69: 'Gold chain',
//   t29: 'Turtleneck jumper',
//   t30: 'Denim jacket',
//   t70: 'Police badge',
//   t408: 'Dress',
//   t28: 'Baseball jersey',
//   t24: 'Leather jacket',
//   t43: 'Sports jacket',
//   t31: 'Basketball jersey',
//   t36: 'Double sword holster',
//   t37: 'Bandolier',
//   t42: 'FLAK vest',
//   t32: 'Dungarees',
//   t27: 'Straight jacket',
//   t158: 'Greek toga',
//   t47: 'High visibility vest',
//   t34: 'Striped t-shirt',
//   t23: 'Army jacket',
//   t52: 'Puffer vest',
//   t38: 'Waistcoat',
//   t35: 'Bulletproof vest',
//   t74: 'Bone necklace',
//   t44: 'Lumberjack shirt',
//   t73: 'Silver chain',
//   t25: 'Prison jumpsuit',
//   t39: 'Hoodie',
//   t41: 'Hawaiian shirt',
//   t402: 'Arrow quiver',
//   t405: 'Lab jacket',
//   t410: 'Leaves',
//   t401: 'Dog tags',
//   t406: 'Safari shirt',
//   t409: 'Camouflage t-shirt',
//   t411: 'Tanktop',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t403: 'Claw mark t-shirt',
//   t120: 'Crown',
//   t146: 'Nightvision helmet',
//   t121: 'Roman helmet',
//   t123: 'Soccer helmet',
//   t124: 'Viking helmet',
//   t125: 'Boxing headgear',
//   t152: 'Dreadlocks',
//   t127: 'Skating helmet',
//   t154: 'Mohawk',
//   t126: 'Beret',
//   t151: 'Punk hair',
//   t135: 'Trapper hat',
//   t153: 'Man bun',
//   t137: 'Headphones',
//   t131: 'Top hat',
//   t129: 'Military hat',
//   t138: 'Vizor hat',
//   t128: 'Sailors hat',
//   t140: 'Beenie hat',
//   t145: 'Combat helmet',
//   t133: 'Pirates hat',
//   t143: 'Turban',
//   t148: 'Long hair',
//   t144: 'Hard hat',
//   t141: 'Bandana',
//   t132: 'Cowboy hat',
//   t130: 'Straw hat',
//   t147: 'Roman leaf crown',
//   t122: 'Spike helmet',
//   t139: 'Bucket hat',
//   t142: 'Baseball hat',
//   t136: 'Backwards hat',
//   t134: 'Bobble hat',
//   t654: 'Safari hat',
//   t655: 'Bamboo hat',
// };

//warthog
// export const names_list: any = {
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//
//   t1: 'Gold',
//   t2: 'Lava',
//   t165: 'Rainbow',
//   t163: 'Futuristic',
//   t164: 'Cheetah',
//   t4: 'Zombie',
//   t3: 'Robot',
//   t333: 'Pink',
//   t5: 'Cream',
//   t6: 'Red',
//   t7: 'Grey',
//   t166: 'Dark brown',
//   t8: 'Brown',
//
//   t76: 'Tongue out',
//   t83: 'Wonky teeth',
//   t78: 'Rainbow teeth',
//   t79: 'Gold teeth',
//   t80: 'Silver teeth',
//   t81: 'Mouth open',
//   t161: 'Grin',
//   t162: 'Scary smile',
//   t75: 'Sewn mouth',
//   t82: 'Goofy smile',
//   t77: 'Blowing',
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t109: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t111: 'Green',
//   t108: 'Fire',
//   t115: 'Multicoloured',
//   t116: 'Cross',
//   t119: 'Red hypnotised',
//   t112: 'Wide eyed',
//   t114: 'Sleepy',
//   t110: 'Bloodshot',
//   t113: 'Black hypnotised',
//   t160: 'Plague',
//   t59: 'Hazard helmet',
//   t64: 'Clown',
//   t65: 'Horror',
//   t55: 'Oxygen mask',
//   t56: 'Jigsaw',
//   t58: 'Balaclava',
//   t159: 'Machine',
//   t54: 'Cyborg',
//   t62: 'Half skeleton',
//   t57: 'Half skull',
//   t60: 'Gas mask',
//   t63: 'Leather',
//   t102: 'Spiked earring',
//   t100: 'Feather earring',
//   t101: 'Gold earring',
//   t103: 'Earphones',
//   t104: 'Silver bar earring',
//   t105: 'Stud earrings',
//   t85: 'Robot eye',
//   t87: 'AR glasses',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t86: 'Bandage',
//   t89: 'Sunglasses',
//   t93: 'Ski mask',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t94: 'Eye patch',
//   t95: 'Reading glasses',
//   t98: 'Scar',
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//   t13: 'Jedi cape',
//   t71: 'Futuristic',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t53: 'Pilot jacket',
//   t26: 'Bathrobe',
//   t18: 'Fur coat',
//   t20: 'Captain jacket',
//   t22: 'Jumper',
//   t68: 'Dollar chain',
//   t188: 'Mummy',
//   t19: 'Navy jacket',
//   t17: 'Military jacket',
//   t33: 'Puffa jacket',
//   t15: 'Tuxedo',
//   t157: 'Spiked armour',
//   t51: 'Dinner suit',
//   t48: 'Shirt & sweater',
//   t50: 'Body armor',
//   t72: 'Clock chain',
//   t69: 'Gold chain',
//   t29: 'Turtleneck jumper',
//   t30: 'Denim jacket',
//   t70: 'Police badge',
//   t408: 'Dress',
//   t28: 'Baseball jersey',
//   t24: 'Leather jacket',
//   t43: 'Sports jacket',
//   t31: 'Basketball jersey',
//   t36: 'Double sword holster',
//   t37: 'Bandolier',
//   t42: 'FLAK vest',
//   t32: 'Dungarees',
//   t27: 'Straight jacket',
//   t158: 'Greek toga',
//   t47: 'High visibility vest',
//   t34: 'Striped t-shirt',
//   t23: 'Army jacket',
//   t52: 'Puffer vest',
//   t38: 'Waistcoat',
//   t822: 'Ripped t-shirt',
//   t35: 'Bulletproof vest',
//   t74: 'Bone necklace',
//   t44: 'Lumberjack shirt',
//   t73: 'Silver chain',
//   t25: 'Prison jumpsuit',
//   t39: 'Hoodie',
//   t41: 'Hawaiian shirt',
//   t402: 'Arrow quiver',
//   t405: 'Lab jacket',
//   t410: 'Leaves',
//   t401: 'Dog tags',
//   t406: 'Safari shirt',
//   t409: 'Camouflage t-shirt',
//   t411: 'Tanktop',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t403: 'Claw mark t-shirt',
//   t120: 'Crown',
//   t146: 'Nightvision helmet',
//   t121: 'Roman helmet',
//   t123: 'Soccer helmet',
//   t124: 'Viking helmet',
//   t125: 'Boxing headgear',
//   t152: 'Dreadlocks',
//   t127: 'Skating helmet',
//   t154: 'Mohawk',
//   t126: 'Bowler hat',
//   t151: 'Punk hair',
//   t135: 'Trapper hat',
//   t153: 'Man bun',
//   t137: 'Headphones',
//   t131: 'Top hat',
//   t129: 'Military hat',
//   t138: 'Keffiyeh',
//   t128: 'Sailors hat',
//   t140: 'Beenie hat',
//   t145: 'Combat helmet',
//   t133: 'Pirates hat',
//   t143: 'Turban',
//   t148: 'Long hair',
//   t144: 'Hard hat',
//   t141: 'Bandana',
//   t132: 'Cowboy hat',
//   t130: 'Straw hat',
//   t147: 'Roman leaf crown',
//   t122: 'Spike helmet',
//   t139: 'Bucket hat',
//   t142: 'Baseball hat',
//   t136: 'Backwards hat',
//   t134: 'Flat cap',
//   t654: 'Safari hat',
//   t655: 'Bamboo hat',
// };

// export const names_list: any = {
//   b1: 'Gold',
//   b2: 'Red',
//   b3: 'Blue',
//   b4: 'Pink',
//   b5: 'Purple',
//   b6: 'Green',
//   b7: 'Aqua',
//   b8: 'Grey',
//   t1: 'Gold',
//   t2: 'Lava',
//   t165: 'Rainbow',
//   t163: 'Futuristic',
//   t164: 'Cheetah',
//   t4: 'Zombie',
//   t3: 'Robot',
//   t333: 'Pink',
//   t5: 'Cream',
//   t6: 'Red',
//   t7: 'Striped',
//   t166: 'Dark grey',
//   t8: 'Grey',
//   t76: 'Tongue out',
//   t83: 'Missing teeth',
//   t78: 'Rainbow teeth',
//   t79: 'Gold teeth',
//   t80: 'Silver teeth',
//   t81: 'Goofy smile',
//   t161: 'Grin',
//   t162: 'Scary smile',
//   t75: 'Sewn mouth',
//   t82: 'Side smile',
//   t77: 'Blowing',
//   t106: 'Eyeball out',
//   t107: 'One eye',
//   t118: 'Orange hypnotised',
//   t109: 'Futuristic',
//   t117: 'Blue hypnotised',
//   t111: 'Green',
//   t108: 'Fire',
//   t115: 'Multicoloured',
//   t116: 'Cross',
//   t119: 'Red hypnotised',
//   t112: 'Wide eyed',
//   t114: 'Sleepy',
//   t110: 'Bloodshot',
//   t113: 'Black hypnotised',
//   t160: 'Plague',
//   t58: 'Balaclava',
//   t159: 'Oxygen mask',
//   t62: 'Half skeleton',
//   t60: 'Gas mask',
//   t63: 'Leather',
//   t102: 'Spiked earring',
//   t100: 'Feather earring',
//   t101: 'Gold earring',
//   t103: 'Earphones',
//   t104: 'Silver bar earring',
//   t105: 'Stud earrings',
//   t85: 'Robot eye',
//   t612: 'Futuristic glasses',
//   t87: 'AR glasses',
//   t97: 'Eyebrow bar',
//   t99: '3D glasses',
//   t86: 'Bandage',
//   t89: 'Masquerade mask',
//   t611: 'Sunglasses',
//   t93: 'Ski mask',
//   t96: 'Eyebrow ring',
//   t84: 'Cyborg eye',
//   t88: 'Disco glasses',
//   t90: 'Bandit mask',
//   t91: 'Aviator glasses',
//   t92: 'Goggles',
//   t94: 'Eye patch',
//   t95: 'Reading glasses',
//   t98: 'Scar',
//   t66: 'Nose bar',
//   t67: 'Nose ring',
//   t656: 'Bone',
//   t13: 'Jedi cape',
//   t71: 'Futuristic',
//   t16: 'Robot claws',
//   t21: 'Knight armour',
//   t45: 'Smoking jacket',
//   t53: 'Pilot jacket',
//   t26: 'Bathrobe',
//   t18: 'Fur coat',
//   t20: 'Captain jacket',
//   t22: 'Jumper',
//   t68: 'Dollar chain',
//   t188: 'Mummy',
//   t19: 'Navy jacket',
//   t17: 'Military jacket',
//   t33: 'Puffa jacket',
//   t15: 'Tuxedo',
//   t157: 'Spiked armour',
//   t51: 'Dinner suit',
//   t48: 'Shirt & sweater',
//   t50: 'Body armor',
//   t72: 'Clock chain',
//   t69: 'Gold chain',
//   t29: 'Turtleneck jumper',
//   t30: 'Denim jacket',
//   t70: 'Police badge',
//   t408: 'Dress',
//   t28: 'Baseball jersey',
//   t24: 'Leather jacket',
//   t43: 'Sports jacket',
//   t31: 'Basketball jersey',
//   t36: 'Double sword holster',
//   t37: 'Bandolier',
//   t42: 'FLAK vest',
//   t32: 'Dungarees',
//   t27: 'Straight jacket',
//   t158: 'Greek toga',
//   t47: 'High visibility vest',
//   t34: 'Striped t-shirt',
//   t23: 'Army jacket',
//   t52: 'Puffer vest',
//   t38: 'Waistcoat',
//   t678: 'T-shirt',
//   t677: 'Ripped t-shirt',
//   t35: 'Bulletproof vest',
//   t74: 'Bone necklace',
//   t44: 'Lumberjack shirt',
//   t73: 'Silver chain',
//   t25: 'Prison jumpsuit',
//   t39: 'Hoodie',
//   t41: 'Hawaiian shirt',
//   t402: 'Arrow quiver',
//   t405: 'Lab jacket',
//   t410: 'Leaves',
//   t401: 'Dog tags',
//   t644: 'Straw top',
//   t406: 'Safari shirt',
//   t409: 'Camouflage t-shirt',
//   t645: 'Fur waistcoat',
//   t712: 'Medieval armour',
//   t411: 'Tanktop',
//   t407: 'Neckerchief',
//   t404: 'Caveman pelt',
//   t403: 'Claw mark t-shirt',
//   t120: 'Crown',
//   t146: 'Nightvision helmet',
//   t121: 'Roman helmet',
//   t123: 'Soccer helmet',
//   t124: 'Viking helmet',
//   t125: 'Boxing headgear',
//   t152: 'Dreadlocks',
//   t127: 'Skating helmet',
//   t154: 'Mohawk',
//   t126: 'Combat helmet',
//   t151: 'Punk hair',
//   t911: 'Flat cap',
//   t135: 'Trapper hat',
//   t153: 'Man bun',
//   t137: 'Headphones',
//   t131: 'Top hat',
//   t129: 'Military hat',
//   t138: 'Vizor hat',
//   t128: 'Sailors hat',
//   t140: 'Beenie hat',
//   t145: 'Kaffiyeh',
//   t133: 'Pirates hat',
//   t143: 'Turban',
//   t148: 'Long hair',
//   t144: 'Hard hat',
//   t141: 'Bandana',
//   t132: 'Cowboy hat',
//   t130: 'Straw hat',
//   t147: 'Roman leaf crown',
//   t122: 'Spike helmet',
//   t872: 'Beret',
//   t139: 'Bucket hat',
//   t142: 'Baseball hat',
//   t136: 'Backwards hat',
//   t134: 'Bobble hat',
//   t654: 'Safari hat',
//   t655: 'Bamboo hat',
//   t57: 'Half skull',
// };

export const names_list: any = {
  b1: 'Gold',
  b2: 'Red',
  b3: 'Blue',
  b4: 'Pink',
  b5: 'Purple',
  b6: 'Green',
  b7: 'Aqua',
  b8: 'Grey',
  t1: 'Gold',
  t2: 'Lava',
  t165: 'Rainbow',
  t163: 'Futuristic',
  t164: 'Grey',
  t4: 'Zombie',
  t3: 'Robot',
  t333: 'Pink',
  t5: 'Cream',
  t6: 'Red',
  t7: 'Striped',
  t166: 'Brown',
  t8: 'Light brown',
  t76: 'Tongue out',
  t83: 'Missing teeth',
  t78: 'Rainbow teeth',
  t79: 'Gold teeth',
  t80: 'Silver teeth',
  t81: 'Goofy smile',
  t161: 'Grin',
  t162: 'Scary smile',
  t75: 'Sewn mouth',
  t82: 'Side smile',
  t77: 'Blowing',
  t106: 'Eyeball out',
  t107: 'One eye',
  t118: 'Orange hypnotised',
  t109: 'Futuristic',
  t117: 'Blue hypnotised',
  t111: 'Green',
  t108: 'Fire',
  t115: 'Multicoloured',
  t116: 'Cross',
  t119: 'Red hypnotised',
  t112: 'Wide eyed',
  t114: 'Sleepy',
  t110: 'Bloodshot',
  t113: 'Black hypnotised',
  t160: 'Plague',
  t59: 'Hazard helmet',
  t64: 'Clown',
  t65: 'Horror',
  t55: 'Robot',
  t56: 'Jigsaw',
  t58: 'Balaclava',
  t159: 'Oxygen mask',
  t61: 'Guy Fawkes',
  t54: 'Cyborg',
  t62: 'Half skeleton',
  t57: 'Half skull',
  t60: 'Gas mask',
  t63: 'Leather',
  t102: 'Spiked earring',
  t100: 'Feather earring',
  t101: 'Gold earring',
  t103: 'Earphones',
  t104: 'Gold bar earring',
  t105: 'Stud earrings',
  t85: 'Robot eye',
  t87: 'AR glasses',
  t97: 'Eyebrow bar',
  t99: '3D glasses',
  t86: 'Bandage',
  t89: 'Masquerade mask',
  t93: 'Ski mask',
  t96: 'Eyebrow ring',
  t84: 'Cyborg eye',
  t88: 'Disco glasses',
  t90: 'Bandit mask',
  t91: 'Aviator glasses',
  t92: 'Goggles',
  t94: 'Eye patch',
  t95: 'Reading glasses',
  t98: 'Scar',
  t66: 'Nose bar',
  t67: 'Nose ring',
  t656: 'Bone',
  t13: 'Jedi cape',
  t71: 'Futuristic',
  t16: 'Robot claws',
  t21: 'Knight armour',
  t45: 'Smoking jacket',
  t53: 'Pilot jacket',
  t26: 'Bathrobe',
  t18: 'Fur coat',
  t20: 'Captain jacket',
  t22: 'Jumper',
  t68: 'Dollar chain',
  t188: 'Mummy',
  t19: 'Navy jacket',
  t17: 'Military jacket',
  t33: 'Puffa jacket',
  t15: 'Tuxedo',
  t157: 'Spiked armour',
  t51: 'Dinner suit',
  t48: 'Shirt & sweater',
  t50: 'Body armor',
  t72: 'Clock chain',
  t69: 'Gold chain',
  t29: 'Turtleneck jumper',
  t30: 'Denim jacket',
  t70: 'Police badge',
  t408: 'Dress',
  t28: 'Baseball jersey',
  t24: 'Leather jacket',
  t43: 'Sports jacket',
  t31: 'Basketball jersey',
  t36: 'Double sword holster',
  t37: 'Bandolier',
  t42: 'FLAK vest',
  t32: 'Dungarees',
  t27: 'Straight jacket',
  t158: 'Greek toga',
  t47: 'High visibility vest',
  t34: 'Striped t-shirt',
  t23: 'Army jacket',
  t52: 'Puffer vest',
  t38: 'Waistcoat',
  t35: 'Bulletproof vest',
  t74: 'Bone necklace',
  t44: 'Lumberjack shirt',
  t73: 'Silver chain',
  t25: 'Prison jumpsuit',
  t39: 'Hoodie',
  t41: 'Hawaiian shirt',
  t402: 'Arrow quiver',
  t913: 'Tribal tunic',
  t912: 'Tribal armor',
  t405: 'Lab jacket',
  t410: 'Leaves',
  t401: 'Dog tags',
  t644: 'Straw top',
  t406: 'Safari shirt',
  t409: 'Camouflage t-shirt',
  t645: 'Fur waistcoat',
  t712: 'Medieval armour',
  t411: 'Tanktop',
  t407: 'Neckerchief',
  t404: 'Caveman pelt',
  t403: 'Claw mark t-shirt',
  t120: 'Crown',
  t146: 'Nightvision helmet',
  t121: 'Roman helmet',
  t123: 'Soccer helmet',
  t124: 'Viking helmet',
  t125: 'Boxing headgear',
  t152: 'Flat cap',
  t127: 'Skating helmet',
  t154: 'Mohawk',
  t126: 'Combat helmet',
  t911: 'Twill cap',
  t135: 'Trapper hat',
  t137: 'Headphones',
  t131: 'Bowler hat',
  t129: 'Military hat',
  t138: 'Vizor hat',
  t128: 'Sailors hat',
  t140: 'Beenie hat',
  t145: 'Kaffiyeh',
  t133: 'Pirates hat',
  t143: 'Turban',
  t144: 'Hard hat',
  t141: 'Bandana',
  t132: 'Cowboy hat',
  t130: 'Straw hat',
  t147: 'Roman leaf crown',
  t122: 'Spike helmet',
  t872: 'Beret',
  t139: 'Bucket hat',
  t142: 'Baseball hat',
  t136: 'Backwards hat',
  t134: 'Bobble hat',
  t148: 'Fedora',
  t654: 'Safari hat',
  t655: 'Bamboo hat',
};

export const getTraitName = (name: string) => {
  if (names_list[name]) {
    return names_list[name];
  }
  console.log('ERROR NOT FOUND NAME: ' + name);
  return '';
};
